import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useEffect } from "react";
import { useRouter } from "expo-router";
import Animated, { FadeInDown } from "react-native-reanimated";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useEss } from "@/lib/ess-workspace";
import { useLumen } from "@/lib/lumen-workspace";
import { trpc } from "@/lib/trpc";
import { clerkEnabled, useOptionalAuth, useOptionalClerk } from "@/lib/pmec-clerk-optional";

export default function EssLoginScreen() {
  const router = useRouter(); const { employee, signIn } = useEss(); const { palette } = useLumen(); const styles = useMemo(() => makeStyles(palette), [palette]); const { isLoaded: clerkLoaded, isSignedIn } = useOptionalAuth(); const { openSignIn, signOut } = useOptionalClerk(); const clerkAccess = trpc.pmecAccess.me.useQuery(undefined, { enabled: clerkLoaded && isSignedIn, retry: false }); const [employeeNumber, setEmployeeNumber] = useState(""); const [pin, setPin] = useState(""); const [error, setError] = useState("");
  const hasEmployeeAccess = clerkAccess.data?.permissions.includes("assignment.read_own") === true;
  useEffect(() => { if (!clerkLoaded || !isSignedIn || clerkAccess.isLoading) return; if (hasEmployeeAccess) { signIn(employee.employeeNumber, employee.pin); router.replace("/(tabs)"); return; } if (clerkAccess.error || clerkAccess.data) setError("This Clerk account is not an employee demo account. Use the PM or HR showcase link instead."); }, [clerkAccess.data, clerkAccess.error, clerkAccess.isLoading, clerkLoaded, employee.employeeNumber, employee.pin, hasEmployeeAccess, isSignedIn, router, signIn]);
  const login = () => { if (signIn(employeeNumber, pin)) { haptic.success(); router.replace("/(tabs)"); } else { haptic.light(); setError("That employee number and PIN do not match."); } };
  const demo = () => { setEmployeeNumber(employee.employeeNumber); setPin(employee.pin); setError(""); };
  return <ScreenContainer containerClassName={styles.container} edges={["top", "bottom", "left", "right"]}><View style={styles.root}><Animated.View entering={FadeInDown.duration(280)}><Text style={styles.kicker}>PMEC / EMPLOYEE SHOWCASE</Text><Text style={styles.title}>WELCOME{`\n`}BACK.</Text><Text style={styles.body}>Sign in with your PMEC employee demonstration account to view your assigned work, submitted hours, and notifications.</Text></Animated.View><View style={styles.form}>{clerkEnabled ? <><Pressable accessibilityRole="button" disabled={!clerkLoaded || clerkAccess.isLoading} onPress={() => openSignIn()} style={({ pressed }) => [styles.clerkButton, pressed && styles.pressed, (!clerkLoaded || clerkAccess.isLoading) && styles.disabled]}><Text style={styles.clerkButtonText}>{isSignedIn ? clerkAccess.isLoading ? "VERIFYING EMPLOYEE ACCESS…" : "OPENING EMPLOYEE WORKSPACE…" : "SIGN IN WITH CLERK →"}</Text></Pressable><Text style={styles.clerkNote}>Employee role only · verified PMEC membership required</Text>{isSignedIn && !hasEmployeeAccess && !clerkAccess.isLoading ? <Pressable onPress={() => signOut()} style={styles.signOut}><Text style={styles.signOutText}>SIGN OUT OF THIS ACCOUNT</Text></Pressable> : null}<View style={styles.localDivider}><View style={styles.dividerLine} /><Text style={styles.dividerText}>LOCAL PROTOTYPE FALLBACK</Text><View style={styles.dividerLine} /></View></> : null}<Text style={styles.fieldLabel}>EMPLOYEE NUMBER</Text><TextInput accessibilityLabel="Employee number" autoCapitalize="none" keyboardType="number-pad" onChangeText={setEmployeeNumber} placeholder="e.g. 76" placeholderTextColor={palette.muted} style={styles.input} value={employeeNumber} /><Text style={styles.fieldLabel}>FOUR-DIGIT PIN</Text><TextInput accessibilityLabel="PIN" keyboardType="number-pad" maxLength={4} onChangeText={setPin} placeholder="••••" placeholderTextColor={palette.muted} secureTextEntry style={styles.input} value={pin} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable accessibilityRole="button" onPress={login} style={({ pressed }) => [styles.loginButton, pressed && styles.pressed]}><Text style={styles.loginText}>OPEN LOCAL PROTOTYPE</Text><Text style={styles.loginArrow}>→</Text></Pressable><Pressable onPress={demo} style={styles.demo}><Text style={styles.demoText}>USE LOCAL FALLBACK: #{employee.employeeNumber} / {employee.pin}</Text></Pressable></View><Text style={styles.footer}>PRODUCTION SHOWCASE · CLERK ROLE ACCESS IS ENFORCED SERVER-SIDE</Text></View></ScreenContainer>;
}
const makeStyles = (palette: ReturnType<typeof useLumen>["palette"]) => StyleSheet.create({ container: { backgroundColor: palette.background }, root: { flex: 1, paddingHorizontal: 24, paddingVertical: 18 }, kicker: { color: palette.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1.15, marginTop: 16 }, title: { color: palette.foreground, fontSize: 47, fontWeight: "900", letterSpacing: -2.2, lineHeight: 51, marginTop: 12 }, body: { color: palette.muted, fontSize: 16, lineHeight: 23, marginTop: 13, maxWidth: 310 }, form: { marginTop: "auto", paddingBottom: 28 }, clerkButton: { alignItems: "center", backgroundColor: palette.accent, borderRadius: 18, height: 58, justifyContent: "center", marginTop: 22 }, clerkButtonText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900", letterSpacing: 1 }, clerkNote: { color: palette.muted, fontSize: 9, fontWeight: "900", letterSpacing: .55, marginTop: 10, textAlign: "center" }, signOut: { alignItems: "center", paddingTop: 13 }, signOutText: { color: palette.accent, fontSize: 9, fontWeight: "900", letterSpacing: .7 }, localDivider: { alignItems: "center", flexDirection: "row", gap: 9, marginTop: 23 }, dividerLine: { backgroundColor: palette.border, flex: 1, height: StyleSheet.hairlineWidth }, dividerText: { color: palette.muted, fontSize: 8, fontWeight: "900", letterSpacing: .6 }, fieldLabel: { color: palette.muted, fontSize: 10, fontWeight: "900", letterSpacing: 0.9, marginTop: 17 }, input: { borderBottomColor: palette.border, borderBottomWidth: 1, color: palette.foreground, fontSize: 20, fontWeight: "800", height: 53, letterSpacing: 0.2 }, error: { color: palette.accent, fontSize: 12, fontWeight: "700", marginTop: 14 }, loginButton: { alignItems: "center", backgroundColor: palette.foreground, borderRadius: 18, flexDirection: "row", height: 58, justifyContent: "center", marginTop: 20 }, loginText: { color: palette.inverseText, fontSize: 11, fontWeight: "900", letterSpacing: 1 }, loginArrow: { color: palette.accent, fontSize: 20, marginLeft: 9 }, demo: { alignItems: "center", paddingTop: 16 }, demoText: { color: palette.accent, fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, footer: { color: palette.muted, fontSize: 9, fontWeight: "900", letterSpacing: 0.8, textAlign: "center" }, pressed: { opacity: 0.87, transform: [{ scale: 0.98 }] }, disabled: { opacity: .5 } });
