import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import Animated, { FadeInDown } from "react-native-reanimated";
import { ScreenContainer } from "@/components/screen-container";
import { useEss } from "@/lib/ess-workspace";
import { useLumen } from "@/lib/lumen-workspace";

const slides = [{ label: "YOUR DAY, IN FOCUS", title: "Work with calm, not noise.", body: "Attendance, projects, and everyday work in one quiet place." }, { label: "KEEP TIME HONEST", title: "Clock into the work that matters.", body: "Choose your project, keep your hours clear, and stay in step." }, { label: "YOUR WORK, YOURS", title: "A better view of the day ahead.", body: "Leave, payslips, personal plans, and daily priorities—stored on your device." }];

export default function EssOnboardingScreen() {
  const router = useRouter(); const { completeOnboarding } = useEss(); const { palette } = useLumen(); const [index, setIndex] = useState(0); const slide = slides[index];
  const finish = () => { completeOnboarding(); router.replace("/ess/login"); };
  return <ScreenContainer containerClassName={{ backgroundColor: palette.background }} edges={["top", "bottom", "left", "right"]}><View style={[styles.root, { backgroundColor: palette.background }]}><View style={styles.top}><Text style={[styles.brand, { color: palette.foreground }]}>LUMEN / PMEC</Text><Text style={[styles.step, { color: palette.muted }]}>{String(index + 1).padStart(2, "0")} / 03</Text></View><Animated.View entering={FadeInDown.duration(320)} key={slide.title} style={styles.copy}><View style={[styles.mark, { backgroundColor: palette.accent }]} /><Text style={[styles.label, { color: palette.accentText }]}>{slide.label}</Text><Text style={[styles.title, { color: palette.foreground }]}>{slide.title}</Text><Text style={[styles.body, { color: palette.muted }]}>{slide.body}</Text></Animated.View><View style={styles.bottom}><View style={styles.dots}>{slides.map((item, dotIndex) => <View key={item.title} style={[styles.dot, { backgroundColor: dotIndex === index ? palette.foreground : palette.border }]} />)}</View><Pressable accessibilityRole="button" onPress={() => index === slides.length - 1 ? finish() : setIndex(index + 1)} style={({ pressed }) => [styles.button, { backgroundColor: palette.foreground }, pressed && styles.pressed]}><Text style={[styles.buttonText, { color: palette.inverseText }]}>{index === slides.length - 1 ? "ENTER WORKSPACE" : "CONTINUE"}</Text><Text style={[styles.arrow, { color: palette.accentText }]}>→</Text></Pressable><Pressable onPress={finish} style={styles.skip}><Text style={[styles.skipText, { color: palette.muted }]}>SKIP INTRO</Text></Pressable></View></View></ScreenContainer>;
}
const styles = StyleSheet.create({ root: { flex: 1, paddingHorizontal: 24, paddingVertical: 18 }, top: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, brand: { fontSize: 11, fontWeight: "900", letterSpacing: 1.1 }, step: { fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, copy: { marginTop: "auto", paddingBottom: 66 }, mark: { height: 6, marginBottom: 22, width: 56 }, label: { fontSize: 10, fontWeight: "900", letterSpacing: 1.15, marginBottom: 12 }, title: { fontSize: 44, fontWeight: "900", letterSpacing: -1.9, lineHeight: 49, maxWidth: 335 }, body: { fontSize: 17, lineHeight: 25, marginTop: 18, maxWidth: 315 }, bottom: { gap: 15 }, dots: { flexDirection: "row", gap: 6 }, dot: { borderRadius: 3, height: 6, width: 26 }, button: { alignItems: "center", borderRadius: 19, flexDirection: "row", height: 59, justifyContent: "center" }, buttonText: { fontSize: 11, fontWeight: "900", letterSpacing: 1 }, arrow: { fontSize: 20, marginLeft: 10 }, skip: { alignItems: "center", padding: 9 }, skipText: { fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, pressed: { opacity: 0.84, transform: [{ scale: 0.98 }] } });
