import { BackButton } from "@/components/pmec";
import { useMemo } from "react";
import { FlatList, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useEss } from "@/lib/ess-workspace";
import { useLumen } from "@/lib/lumen-workspace";

export default function ActivityScreen() { const { activity } = useEss(); const { palette } = useLumen(); const styles = useMemo(() => makeStyles(palette), [palette]); return <ScreenContainer containerClassName={styles.container} edges={["top", "left", "right"]}><FlatList data={activity} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.top}><BackButton fallback="/settings" label="Back to Profile" /><Text style={styles.topLabel}>RECENT MOMENTS</Text></View><View style={styles.hero}><Text style={styles.kicker}>LOCAL RECORD</Text><Text style={styles.title}>ACTIVITY</Text><Text style={styles.subtitle}>A small, clear history of your workday.</Text></View></>} renderItem={({ item }) => <View style={styles.row}><View style={[styles.mark, { backgroundColor: item.tone === "success" ? palette.success : item.tone === "accent" ? palette.accent : palette.border }]} /><View style={styles.copy}><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.detail}>{item.detail}</Text><Text style={styles.date}>{item.createdAt}</Text></View></View>} /></ScreenContainer>; }
const makeStyles = (palette: ReturnType<typeof useLumen>["palette"]) => StyleSheet.create({ container:{backgroundColor:palette.background},content:{paddingBottom:25},top:{alignItems:"center",flexDirection:"row",gap:12,paddingHorizontal:18,paddingTop:10},back:{alignItems:"center",borderColor:palette.border,borderRadius:16,borderWidth:1,height:34,justifyContent:"center",width:34},backText:{color:palette.foreground,fontSize:20},topLabel:{color:palette.muted,fontSize:10,fontWeight:"900",letterSpacing:1},hero:{borderBottomColor:palette.border,borderBottomWidth:StyleSheet.hairlineWidth,paddingHorizontal:22,paddingBottom:26,paddingTop:27},kicker:{color:palette.accent,fontSize:10,fontWeight:"900",letterSpacing:1.1},title:{color:palette.foreground,fontSize:44,fontWeight:"900",letterSpacing:-2,lineHeight:49,marginTop:9},subtitle:{color:palette.muted,fontSize:15,lineHeight:21,marginTop:8},row:{borderBottomColor:palette.border,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:"row",gap:13,minHeight:80,paddingHorizontal:22,paddingVertical:17},mark:{borderRadius:3,height:36,width:5},copy:{flex:1},itemTitle:{color:palette.foreground,fontSize:16,fontWeight:"900"},detail:{color:palette.muted,fontSize:13,lineHeight:18,marginTop:4},date:{color:palette.muted,fontSize:9,fontWeight:"900",letterSpacing:0.5,marginTop:7} });
