import { BackButton } from "@/components/pmec";
import { useMemo } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useEss } from "@/lib/ess-workspace";
import { useEmployeeProjects } from "@/lib/pmec-employee-data";
import { useLumen } from "@/lib/lumen-workspace";

export default function AnalyticsScreen(){const {attendance}=useEss();const {projects}=useEmployeeProjects();const {palette}=useLumen();const styles=useMemo(()=>makeStyles(palette),[palette]);const completed=projects.flatMap((project)=>project.phases.flatMap((phase)=>phase.tasks)).filter((task)=>task.status==="done").length;const total=projects.flatMap((project)=>project.phases.flatMap((phase)=>phase.tasks)).length;const late=attendance.filter((item)=>item.late).length;return <ScreenContainer containerClassName={styles.container} edges={["top","left","right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><BackButton fallback="/settings" label="Back to Profile" /><Text style={styles.topLabel}>YOUR PATTERNS</Text></View><View style={styles.hero}><Text style={styles.kicker}>LOCAL SNAPSHOT</Text><Text style={styles.title}>ANALYSE</Text><Text style={styles.subtitle}>A clear view of the work you have recorded.</Text></View><View style={styles.metrics}><View style={styles.metric}><Text style={styles.value}>{attendance.length}</Text><Text style={styles.metricLabel}>DAYS RECORDED</Text></View><View style={styles.metric}><Text style={styles.value}>{Math.round(completed/total*100)}%</Text><Text style={styles.metricLabel}>TASKS COMPLETE</Text></View><View style={styles.metric}><Text style={styles.value}>{late}</Text><Text style={styles.metricLabel}>LATE DAYS</Text></View></View><Text style={styles.sectionTitle}>PROJECT BREAKDOWN</Text>{projects.filter((project)=>project.status!=="completed").map((project)=>{const items=project.phases.flatMap((phase)=>phase.tasks);const done=items.filter((task)=>task.status==="done").length;return <View key={project.id} style={styles.project}><View style={[styles.projectMark,{backgroundColor:project.color}]}/><View style={styles.projectCopy}><View style={styles.projectHead}><Text style={styles.projectName}>{project.name}</Text><Text style={styles.projectNumber}>{done}/{items.length}</Text></View><View style={styles.track}><View style={[styles.fill,{backgroundColor:project.color,width:`${Math.round(done/items.length*100)}%`}]} /></View></View></View>})}</ScrollView></ScreenContainer>}
const makeStyles=(palette:ReturnType<typeof useLumen>["palette"])=>StyleSheet.create({container:{backgroundColor:palette.background},content:{paddingBottom:30},top:{alignItems:"center",flexDirection:"row",gap:12,paddingHorizontal:18,paddingTop:10},back:{alignItems:"center",borderColor:palette.border,borderRadius:16,borderWidth:1,height:34,justifyContent:"center",width:34},backText:{color:palette.foreground,fontSize:20},topLabel:{color:palette.muted,fontSize:10,fontWeight:"900",letterSpacing:1},hero:{paddingHorizontal:22,paddingBottom:26,paddingTop:27},kicker:{color: palette.accentText,fontSize:10,fontWeight:"900",letterSpacing:1.1},title:{color:palette.foreground,fontSize:44,fontWeight:"900",letterSpacing:-2,lineHeight:49,marginTop:9},subtitle:{color:palette.muted,fontSize:15,lineHeight:21,marginTop:8},metrics:{borderBottomColor:palette.border,borderTopColor:palette.border,borderBottomWidth:StyleSheet.hairlineWidth,borderTopWidth:StyleSheet.hairlineWidth,flexDirection:"row"},metric:{borderRightColor:palette.border,borderRightWidth:StyleSheet.hairlineWidth,flex:1,minHeight:102,padding:14},value:{color:palette.foreground,fontSize:29,fontWeight:"900",letterSpacing:-1},metricLabel:{color:palette.muted,fontSize:9,fontWeight:"900",letterSpacing:0.55,lineHeight:12,marginTop:8},sectionTitle:{borderBottomColor:palette.border,borderBottomWidth:StyleSheet.hairlineWidth,color:palette.foreground,fontSize:12,fontWeight:"900",letterSpacing:0.8,paddingHorizontal:22,paddingVertical:16},project:{alignItems:"center",borderBottomColor:palette.border,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:"row",gap:12,paddingHorizontal:22,paddingVertical:16},projectMark:{borderRadius:3,height:35,width:5},projectCopy:{flex:1},projectHead:{flexDirection:"row",justifyContent:"space-between"},projectName:{color:palette.foreground,fontSize:15,fontWeight:"900"},projectNumber:{color:palette.muted,fontSize:11,fontWeight:"900"},track:{backgroundColor:palette.surfaceStrong,borderRadius:2,height:5,marginTop:11,overflow:"hidden"},fill:{borderRadius:2,height:5}});
