import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import Animated, { FadeInDown } from "react-native-reanimated";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useEss } from "@/lib/ess-workspace";
import { useLumen } from "@/lib/lumen-workspace";

type Step = "project" | "phase" | "task" | "scan" | "success";
export default function AttendanceScreen() {
  const router = useRouter(); const { clockIn, clockOut, projects, todayAttendance } = useEss(); const { palette } = useLumen(); const styles = useMemo(() => makeStyles(palette), [palette]); const [step, setStep] = useState<Step>(todayAttendance?.clockIn ? "success" : "project"); const [projectId, setProjectId] = useState(""); const [phaseId, setPhaseId] = useState(""); const [taskId, setTaskId] = useState(""); const project = projects.find((item) => item.id === projectId); const phase = project?.phases.find((item) => item.id === phaseId);
  const beginScan = () => { setStep("scan"); setTimeout(() => { clockIn({ projectId, phaseId, taskId: taskId || undefined }); haptic.success(); setStep("success"); }, 2200); };
  const exit = () => router.back();
  if (todayAttendance?.clockIn && !todayAttendance.clockOut && step === "success") return <ScreenContainer containerClassName={styles.container} edges={["top", "bottom", "left", "right"]}><View style={styles.center}><Text style={styles.kicker}>YOU ARE CURRENTLY CLOCKED IN</Text><Text style={styles.title}>WORK{`\n`}IS LIVE.</Text><Text style={styles.body}>Your time is being recorded locally for today.</Text><Pressable onPress={() => { clockOut(); haptic.success(); }} style={({ pressed }) => [styles.primary, pressed && styles.pressed]}><Text style={styles.primaryText}>CLOCK OUT</Text></Pressable><Pressable onPress={exit} style={styles.secondary}><Text style={styles.secondaryText}>RETURN HOME</Text></Pressable></View></ScreenContainer>;
  if (step === "scan") return <ScreenContainer containerClassName={styles.container} edges={["top", "bottom", "left", "right"]}><View style={styles.scanRoot}><Animated.View entering={FadeInDown.duration(250)} style={[styles.scanRing, { borderColor: palette.accent }]}><View style={[styles.scanInner, { backgroundColor: palette.surfaceStrong }]}><Text style={[styles.scanIcon, { color: palette.foreground }]}>◌</Text></View></Animated.View><Text style={styles.kicker}>VERIFYING PRESENCE</Text><Text style={styles.scanTitle}>HOLD STILL.</Text><Text style={styles.body}>A local simulation is confirming your check-in.</Text></View></ScreenContainer>;
  if (step === "success") return <ScreenContainer containerClassName={styles.container} edges={["top", "bottom", "left", "right"]}><View style={styles.center}><View style={[styles.successMark, { backgroundColor: palette.accent }]}><Text style={styles.successText}>✓</Text></View><Text style={styles.kicker}>ATTENDANCE RECORDED</Text><Text style={styles.title}>YOU’RE{`\n`}IN.</Text><Text style={styles.body}>Your project time has been saved to this device.</Text><Pressable onPress={() => router.replace("/(tabs)")} style={({ pressed }) => [styles.primary, pressed && styles.pressed]}><Text style={styles.primaryText}>RETURN HOME</Text></Pressable></View></ScreenContainer>;
  const options: Array<{ id: string; title: string; meta: string; color?: string }> = step === "project" ? projects.filter((item) => item.status !== "completed").map((item) => ({ id: item.id, title: item.name, meta: `${item.code} · ${item.client}`, color: item.color })) : step === "phase" ? (project?.phases ?? []).map((item) => ({ id: item.id, title: item.name, meta: `${item.tasks.length} tasks` })) : (phase?.tasks ?? []).map((item) => ({ id: item.id, title: item.title, meta: item.status.replace("_", " ") }));
  const select = (id: string) => { haptic.selection(); if (step === "project") { setProjectId(id); setStep("phase"); } else if (step === "phase") { setPhaseId(id); setStep("task"); } else { setTaskId(id); beginScan(); } };
  const heading = step === "project" ? ["SELECT PROJECT", "Where are you working?"] : step === "phase" ? ["SELECT PHASE", project?.name ?? ""] : ["SELECT TASK", phase?.name ?? ""];
  return <ScreenContainer containerClassName={styles.container} edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.screen}><Pressable onPress={step === "project" ? exit : () => setStep(step === "phase" ? "project" : "phase")} style={styles.back}><Text style={styles.backText}>←</Text></Pressable><Text style={styles.kicker}>{heading[0]}</Text><Text style={styles.heading}>{heading[1]}</Text><View style={styles.options}>{options.map((item) => <Pressable key={item.id} onPress={() => select(item.id)} style={({ pressed }) => [styles.option, pressed && styles.pressed]}><View style={[styles.optionLine, { backgroundColor: item.color ?? palette.accent }]} /><View style={styles.optionCopy}><Text style={styles.optionTitle}>{item.title}</Text><Text style={styles.optionMeta}>{item.meta.toUpperCase()}</Text></View><Text style={styles.optionArrow}>→</Text></Pressable>)}</View></ScrollView></ScreenContainer>;
}
const makeStyles = (palette: ReturnType<typeof useLumen>["palette"]) => StyleSheet.create({ container: { backgroundColor: palette.background }, screen: { padding: 22 }, back: { alignItems: "center", borderColor: palette.border, borderRadius: 16, borderWidth: 1, height: 34, justifyContent: "center", marginBottom: 25, width: 34 }, backText: { color: palette.foreground, fontSize: 20 }, kicker: { color: palette.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginBottom: 11 }, heading: { color: palette.foreground, fontSize: 36, fontWeight: "900", letterSpacing: -1.5, lineHeight: 42 }, options: { marginTop: 28 }, option: { alignItems: "center", borderBottomColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 12, minHeight: 82, paddingVertical: 12 }, optionLine: { borderRadius: 3, height: 38, width: 5 }, optionCopy: { flex: 1 }, optionTitle: { color: palette.foreground, fontSize: 17, fontWeight: "900", letterSpacing: -0.35 }, optionMeta: { color: palette.muted, fontSize: 10, fontWeight: "800", letterSpacing: 0.7, marginTop: 5 }, optionArrow: { color: palette.foreground, fontSize: 20 }, scanRoot: { alignItems: "center", flex: 1, justifyContent: "center", paddingHorizontal: 32 }, scanRing: { alignItems: "center", borderRadius: 110, borderWidth: 2, height: 218, justifyContent: "center", width: 218 }, scanInner: { alignItems: "center", borderRadius: 86, height: 172, justifyContent: "center", width: 172 }, scanIcon: { fontSize: 72, fontWeight: "200" }, scanTitle: { color: palette.foreground, fontSize: 36, fontWeight: "900", letterSpacing: -1.5, marginTop: 13 }, center: { flex: 1, justifyContent: "center", paddingHorizontal: 28 }, title: { color: palette.foreground, fontSize: 46, fontWeight: "900", letterSpacing: -2.1, lineHeight: 50 }, body: { color: palette.muted, fontSize: 16, lineHeight: 23, marginTop: 14, maxWidth: 285 }, primary: { alignItems: "center", backgroundColor: palette.foreground, borderRadius: 18, justifyContent: "center", marginTop: 31, minHeight: 57 }, primaryText: { color: palette.inverseText, fontSize: 11, fontWeight: "900", letterSpacing: 1 }, secondary: { alignItems: "center", padding: 17 }, secondaryText: { color: palette.muted, fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, successMark: { alignItems: "center", borderRadius: 28, height: 56, justifyContent: "center", marginBottom: 26, width: 56 }, successText: { color: "#FFFFFF", fontSize: 28, fontWeight: "900" }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] } });
