import { useMemo } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Redirect, useRouter } from "expo-router";
import Animated, { FadeInDown } from "react-native-reanimated";

import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useEss } from "@/lib/ess-workspace";
import { useLumen } from "@/lib/lumen-workspace";
import { type SharedNotification, usePmecDeliverySync } from "@/lib/pmec-delivery-sync";

export default function NotificationCenter() {
  const router = useRouter(); const { onboarded, isAuthenticated } = useEss(); const { palette } = useLumen(); const sync = usePmecDeliverySync(); const styles = useMemo(() => makeStyles(palette), [palette]);
  if (!onboarded) return <Redirect href="/ess/onboarding" />; if (!isAuthenticated) return <Redirect href="/ess/login" />;
  const open = async (notification: SharedNotification) => { if (!notification.readAt) await sync.markNotificationRead(notification.id); haptic.light(); router.push(notification.route as never); };
  return <ScreenContainer containerClassName={styles.container} edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Animated.View entering={FadeInDown.duration(220)} style={styles.hero}><Text style={styles.kicker}>PMEC / NOTIFICATIONS</Text><Text style={styles.title}>Delivery{`\n`}updates.</Text><Text style={styles.copy}>New work assignments and approved hours appear here, linked to the right work package.</Text><View style={styles.summary}><Text style={styles.summaryValue}>{sync.unreadNotifications}</Text><Text style={styles.summaryLabel}>UNREAD UPDATE{sync.unreadNotifications === 1 ? "" : "S"}</Text></View></Animated.View><View style={styles.sectionHead}><Text style={styles.sectionTitle}>YOUR UPDATES</Text><Pressable onPress={() => void sync.refresh()}><Text style={styles.refresh}>REFRESH</Text></Pressable></View>{!sync.ready ? <View style={styles.empty}><ActivityIndicator color={palette.accent} /><Text style={styles.emptyCopy}>Checking your PMEC updates…</Text></View> : sync.notifications.length ? sync.notifications.map((notification) => <Pressable key={notification.id} onPress={() => void open(notification)} style={({ pressed }) => [styles.notification, !notification.readAt && styles.unread, pressed && styles.pressed]}><View style={[styles.icon, notification.type === "time_approved" && styles.iconApproved]}><Text style={styles.iconText}>{notification.type === "assignment" ? "WORK" : "TIME"}</Text></View><View style={styles.flex}><Text style={styles.itemTitle}>{notification.title}</Text><Text style={styles.itemBody}>{notification.body}</Text><Text style={styles.meta}>{formatMoment(notification.createdAt)} · {notification.readAt ? "READ" : "NEW"}</Text></View><Text style={styles.arrow}>→</Text></Pressable>) : <View style={styles.empty}><Text style={styles.emptyTitle}>You’re all caught up.</Text><Text style={styles.emptyCopy}>When a project manager assigns PMEC work or approves your submitted time, the update will appear here.</Text></View>}</ScrollView></ScreenContainer>;
}

function formatMoment(value: Date | string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "RECENTLY" : date.toLocaleDateString("en", { month: "short", day: "numeric" }).toUpperCase(); }
const makeStyles = (palette: ReturnType<typeof useLumen>["palette"]) => StyleSheet.create({ container: { backgroundColor: palette.background }, content: { paddingBottom: 34 }, hero: { paddingHorizontal: 22, paddingTop: 20 }, kicker: { color: palette.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, title: { color: palette.foreground, fontSize: 43, fontWeight: "900", letterSpacing: -2.1, lineHeight: 47, marginTop: 11 }, copy: { color: palette.muted, fontSize: 13, lineHeight: 19, marginTop: 12, maxWidth: 330 }, summary: { alignItems: "baseline", backgroundColor: palette.foreground, flexDirection: "row", gap: 10, marginTop: 20, paddingHorizontal: 14, paddingVertical: 12, alignSelf: "flex-start" }, summaryValue: { color: palette.accent, fontSize: 26, fontWeight: "900", letterSpacing: -1 }, summaryLabel: { color: palette.inverseText, fontSize: 9, fontWeight: "900", letterSpacing: .6 }, sectionHead: { alignItems: "center", borderBottomColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", marginTop: 25, paddingHorizontal: 22, paddingBottom: 12 }, sectionTitle: { color: palette.foreground, fontSize: 11, fontWeight: "900", letterSpacing: .7 }, refresh: { color: palette.accent, fontSize: 9, fontWeight: "900", letterSpacing: .5 }, notification: { alignItems: "center", borderBottomColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 12, paddingHorizontal: 22, paddingVertical: 16 }, unread: { backgroundColor: palette.surfaceStrong }, icon: { alignItems: "center", backgroundColor: palette.accent, borderRadius: 10, height: 38, justifyContent: "center", width: 38 }, iconApproved: { backgroundColor: palette.success }, iconText: { color: "#FFFFFF", fontSize: 8, fontWeight: "900", letterSpacing: .35 }, flex: { flex: 1 }, itemTitle: { color: palette.foreground, fontSize: 14, fontWeight: "900" }, itemBody: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 4 }, meta: { color: palette.accent, fontSize: 8, fontWeight: "900", letterSpacing: .45, marginTop: 7 }, arrow: { color: palette.foreground, fontSize: 18 }, empty: { alignItems: "flex-start", backgroundColor: palette.surfaceStrong, gap: 10, margin: 22, padding: 18 }, emptyTitle: { color: palette.foreground, fontSize: 17, fontWeight: "900" }, emptyCopy: { color: palette.muted, fontSize: 12, lineHeight: 18 }, pressed: { opacity: .72 } });
