import { useEssGate } from "@/components/ess-gate";
import { BackButton } from "@/components/pmec";
import { useMemo } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import Animated, { FadeInDown } from "react-native-reanimated";

import { ScreenContainer } from "@/components/screen-container";
import { useLumen } from "@/lib/lumen-workspace";
import { usePmecDeliverySync } from "@/lib/pmec-delivery-sync";

export default function NotificationSettingsScreen() {
  const gate = useEssGate(); const { palette } = useLumen(); const sync = usePmecDeliverySync(); const styles = useMemo(() => makeStyles(palette), [palette]);
  if (gate) return gate;
  const toggle = (key: "assignmentsEnabled" | "timeApprovedEnabled") => void sync.updateNotificationPreferences({ ...sync.notificationPreferences, [key]: !sync.notificationPreferences[key] });
  return <ScreenContainer containerClassName={styles.container} edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><BackButton fallback="/notifications" label="Back to Notifications" style={{ marginLeft: 18, marginTop: 10, marginBottom: 14 }} /><Animated.View entering={FadeInDown.duration(220)} style={styles.hero}><Text style={styles.kicker}>PMEC / SETTINGS</Text><Text style={styles.title}>Update{`\n`}control.</Text><Text style={styles.copy}>Choose which delivery events arrive in your PMEC inbox. You can restore archived updates at any time.</Text></Animated.View><View style={styles.section}><Text style={styles.sectionTitle}>INBOX PREFERENCES</Text><Preference styles={styles} label="New work assignments" detail="When a project manager assigns you a PMEC work package." active={sync.notificationPreferences.assignmentsEnabled} onPress={() => toggle("assignmentsEnabled")} /><Preference styles={styles} label="Hours approved" detail="When your submitted delivery time is approved." active={sync.notificationPreferences.timeApprovedEnabled} onPress={() => toggle("timeApprovedEnabled")} /></View><View style={styles.section}><Text style={styles.sectionTitle}>ARCHIVED UPDATES</Text>{!sync.ready ? <ActivityIndicator color={palette.accent} /> : sync.archivedNotifications.length ? sync.archivedNotifications.map((item) => <View key={item.id} style={styles.archived}><View style={styles.flex}><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.itemCopy}>{item.body}</Text></View><Pressable onPress={() => void sync.restoreNotification(item.id)} style={styles.restore}><Text style={styles.restoreText}>RESTORE</Text></Pressable></View>) : <Text style={styles.empty}>No archived delivery updates.</Text>}</View></ScrollView></ScreenContainer>;
}

function Preference({ styles, label, detail, active, onPress }: any) { return <Pressable onPress={onPress} style={styles.preference}><View style={styles.flex}><Text style={styles.itemTitle}>{label}</Text><Text style={styles.itemCopy}>{detail}</Text></View><View style={[styles.switch, active && styles.switchOn]}><View style={[styles.knob, active && styles.knobOn]} /></View></Pressable>; }
const makeStyles = (palette: ReturnType<typeof useLumen>["palette"]) => StyleSheet.create({ container: { backgroundColor: palette.background }, content: { paddingBottom: 34 }, hero: { paddingHorizontal: 22, paddingTop: 20 }, kicker: { color: palette.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, title: { color: palette.foreground, fontSize: 43, fontWeight: "900", letterSpacing: -2.1, lineHeight: 47, marginTop: 11 }, copy: { color: palette.muted, fontSize: 13, lineHeight: 19, marginTop: 12, maxWidth: 330 }, section: { borderTopColor: palette.border, borderTopWidth: StyleSheet.hairlineWidth, marginTop: 28, paddingHorizontal: 22, paddingTop: 14 }, sectionTitle: { color: palette.foreground, fontSize: 10, fontWeight: "900", letterSpacing: .7, marginBottom: 7 }, preference: { alignItems: "center", borderBottomColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 14, paddingVertical: 16 }, flex: { flex: 1 }, itemTitle: { color: palette.foreground, fontSize: 14, fontWeight: "900" }, itemCopy: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 4 }, switch: { backgroundColor: palette.border, borderRadius: 14, height: 28, padding: 3, width: 50 }, switchOn: { backgroundColor: palette.accent }, knob: { backgroundColor: "#FFFFFF", borderRadius: 11, height: 22, width: 22 }, knobOn: { alignSelf: "flex-end" }, archived: { alignItems: "center", borderBottomColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 12, paddingVertical: 15 }, restore: { borderBottomColor: palette.accent, borderBottomWidth: 1, paddingBottom: 3 }, restoreText: { color: palette.accent, fontSize: 8, fontWeight: "900", letterSpacing: .5 }, empty: { color: palette.muted, fontSize: 12, paddingVertical: 14 } });
