import { BackButton } from "@/components/pmec";
import { useMemo, useState } from "react";
import { Alert, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useEss } from "@/lib/ess-workspace";
import { useLumen } from "@/lib/lumen-workspace";
import { usePmecDeliverySync } from "@/lib/pmec-delivery-sync";

export default function ProfileScreen() { const router = useRouter(); const { employee, resetEssDemo, signOut, updatePin } = useEss(); const { palette, resetWorkspace, setThemeMode, themeMode } = useLumen(); const sync = usePmecDeliverySync(); const styles = useMemo(() => makeStyles(palette), [palette]); const [pin, setPin] = useState(""); const [message, setMessage] = useState(""); const savePin = () => { if (/^\d{4}$/.test(pin)) { updatePin(pin); setPin(""); setMessage("Your local demo PIN has been updated."); haptic.success(); } else setMessage("Choose a four-digit PIN."); }; const logout = () => { signOut(); router.replace("/ess/login"); }; const resetAll = () => { resetEssDemo(); resetWorkspace(); sync.resetShowcase(); router.replace("/ess/login"); }; const reset = () => { const message = "This restores the employee's sample data, tasks and notifications on this device."; if (Platform.OS === "web") { if (typeof window !== "undefined" && window.confirm(`Reset the demo?\n\n${message}`)) resetAll(); return; } Alert.alert("Reset the demo?", message, [{ text: "Cancel", style: "cancel" }, { text: "Reset", style: "destructive", onPress: resetAll }]); };
  return <ScreenContainer containerClassName={styles.container} edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><BackButton fallback="/" label="Back to Home" /><Text style={styles.topLabel}>YOUR SPACE</Text></View><View style={styles.hero}><View style={styles.avatar}><Text style={styles.avatarText}>{employee.firstName.charAt(0)}{employee.lastName.charAt(0)}</Text></View><Text style={styles.name}>{employee.firstName.toUpperCase()} {employee.lastName.toUpperCase()}</Text><Text style={styles.role}>{employee.role} · #{employee.employeeNumber}</Text></View><View style={styles.group}><Text style={styles.groupLabel}>APPEARANCE</Text><View style={styles.themeRow}>{(["light", "dark"] as const).map((mode) => <Pressable key={mode} onPress={() => { haptic.selection(); setThemeMode(mode); }} style={[styles.themeButton, themeMode === mode && styles.themeSelected]}><Text style={[styles.themeText, themeMode === mode && styles.themeTextSelected]}>{mode.toUpperCase()}</Text></Pressable>)}</View></View><View style={styles.group}><Text style={styles.groupLabel}>SECURITY</Text><Text style={styles.groupTitle}>Change local PIN</Text><Text style={styles.groupBody}>This PIN only protects the demo session on this device.</Text><TextInput keyboardType="number-pad" maxLength={4} onChangeText={setPin} placeholder="NEW FOUR-DIGIT PIN" placeholderTextColor={palette.muted} secureTextEntry style={styles.input} value={pin}/>{message ? <Text style={styles.message}>{message}</Text> : null}<Pressable onPress={savePin} style={styles.save}><Text style={styles.saveText}>SAVE PIN</Text></Pressable></View><View style={styles.group}><Text style={styles.groupLabel}>WORKSPACE</Text>{[{ label: "Personal calendar", route: "/personal-calendar" }, { label: "Leave requests", route: "/leave" }, { label: "Analytics", route: "/analytics" }, { label: "Activity", route: "/activity" }].map((item) => <Pressable key={item.label} onPress={() => router.push(item.route as never)} style={styles.link}><Text style={styles.linkText}>{item.label}</Text><Text style={styles.linkArrow}>→</Text></Pressable>)}</View><Pressable onPress={logout} style={styles.logout}><Text style={styles.logoutText}>SIGN OUT</Text></Pressable><Pressable accessibilityRole="button" onPress={reset} style={styles.reset}><Text style={styles.resetText}>RESET DEMO DATA</Text></Pressable></ScrollView></ScreenContainer>; }
const makeStyles = (palette: ReturnType<typeof useLumen>["palette"]) => StyleSheet.create({ container:{backgroundColor:palette.background},content:{paddingBottom:30},top:{alignItems:"center",flexDirection:"row",gap:12,paddingHorizontal:18,paddingTop:10},back:{alignItems:"center",borderColor:palette.border,borderRadius:16,borderWidth:1,height:34,justifyContent:"center",width:34},backText:{color:palette.foreground,fontSize:20},topLabel:{color:palette.muted,fontSize:10,fontWeight:"900",letterSpacing:1},hero:{alignItems:"flex-start",borderBottomColor:palette.border,borderBottomWidth:StyleSheet.hairlineWidth,paddingHorizontal:22,paddingBottom:25,paddingTop:24},avatar:{alignItems:"center",backgroundColor:palette.foreground,borderRadius:29,height:58,justifyContent:"center",width:58},avatarText:{color:palette.inverseText,fontSize:18,fontWeight:"900",letterSpacing:-0.5},name:{color:palette.foreground,fontSize:29,fontWeight:"900",letterSpacing:-1.1,marginTop:14},role:{color:palette.muted,fontSize:13,fontWeight:"700",marginTop:5},group:{borderBottomColor:palette.border,borderBottomWidth:StyleSheet.hairlineWidth,paddingHorizontal:22,paddingVertical:17},groupLabel:{color:palette.muted,fontSize:10,fontWeight:"900",letterSpacing:1,marginBottom:13},groupTitle:{color:palette.foreground,fontSize:16,fontWeight:"900"},groupBody:{color:palette.muted,fontSize:13,lineHeight:19,marginTop:4},themeRow:{flexDirection:"row",gap:8},themeButton:{alignItems:"center",borderColor:palette.border,borderRadius:15,borderWidth:1,justifyContent:"center",minHeight:35,minWidth:68},themeSelected:{backgroundColor:palette.foreground,borderColor:palette.foreground},themeText:{color:palette.muted,fontSize:10,fontWeight:"900",letterSpacing:0.7},themeTextSelected:{color:palette.inverseText},input:{borderBottomColor:palette.border,borderBottomWidth:1,color:palette.foreground,fontSize:16,fontWeight:"900",height:49,letterSpacing:2,marginTop:14},message:{color:palette.accent,fontSize:11,fontWeight:"700",marginTop:9},save:{alignItems:"center",borderColor:palette.border,borderRadius:15,borderWidth:1,justifyContent:"center",marginTop:14,minHeight:42},saveText:{color:palette.foreground,fontSize:10,fontWeight:"900",letterSpacing:0.8},link:{alignItems:"center",borderTopColor:palette.border,borderTopWidth:StyleSheet.hairlineWidth,flexDirection:"row",justifyContent:"space-between",minHeight:49},linkText:{color:palette.foreground,fontSize:15,fontWeight:"800"},linkArrow:{color:palette.accent,fontSize:19},logout:{alignItems:"center",backgroundColor:palette.foreground,borderRadius:18,justifyContent:"center",marginHorizontal:22,marginTop:24,minHeight:55},logoutText:{color:palette.inverseText,fontSize:11,fontWeight:"900",letterSpacing:1},reset:{alignItems:"center",padding:18},resetText:{color:palette.muted,fontSize:9,fontWeight:"900",letterSpacing:0.7} });
