import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, type PropsWithChildren, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { initialWorkspace } from "@/lib/lumen-data";
import { lumenPalettes, type ThemeMode } from "@/lib/lumen-theme";
import type { MotionMode, NewProject, NewTask, Project, Recurrence, Task, TaskPriority, WorkspaceState } from "@/lib/lumen-types";
import { compareTasks, nextOccurrenceDate, nextOccurrenceReminder, normalizeTags } from "@/lib/lumen-utils";

const STORAGE_KEY = "lumen.workspace.v2";
const projectColors = ["#FF5A1F", "#3A7563", "#96734C", "#6059A8", "#B54E70"];
type LumenWorkspace = WorkspaceState & { ready: boolean; palette: (typeof lumenPalettes)[ThemeMode]; toggleTask: (taskId: string) => void; addTask: (draft: NewTask) => void; addProject: (draft: NewProject) => void; setActiveDate: (dateKey: string) => void; setThemeMode: (mode: ThemeMode) => void; setMotionMode: (mode: MotionMode) => void; setFilters: (priority: TaskPriority | "all", tag?: string) => void; setTaskNotificationId: (taskId: string, notificationId?: string) => void; resetWorkspace: () => void; tasksForDate: (dateKey: string) => Task[]; tasksForProject: (projectId: string) => Task[]; projectForTask: (projectId: string) => Project | undefined; allTags: string[] };
const WorkspaceContext = createContext<LumenWorkspace | null>(null);
function isWorkspaceState(value: unknown): value is WorkspaceState { if (!value || typeof value !== "object") return false; const candidate = value as WorkspaceState; return Array.isArray(candidate.projects) && Array.isArray(candidate.tasks) && typeof candidate.activeDate === "string"; }
function hydrateTask(task: Task): Task { return { ...task, tags: normalizeTags(task.tags ?? []), recurrence: task.recurrence ?? "none" }; }
function makeNextTask(task: Task): Task | null { const recurrence = task.recurrence ?? "none"; if (recurrence === "none") return null; const dueDate = nextOccurrenceDate(task.dueDate, recurrence); return { ...task, id: `task-${Date.now()}-${task.id}`, dueDate, reminderAt: nextOccurrenceReminder(task.reminderAt, dueDate), completed: false, completedAt: undefined, notificationId: undefined, createdAt: new Date().toISOString(), recurrenceSourceId: task.recurrenceSourceId ?? task.id }; }

export function LumenWorkspaceProvider({ children }: PropsWithChildren) {
  const [workspace, setWorkspace] = useState<WorkspaceState>(initialWorkspace);
  const [ready, setReady] = useState(false);
  useEffect(() => { const restore = async () => { try { const stored = await AsyncStorage.getItem(STORAGE_KEY) ?? await AsyncStorage.getItem("lumen.workspace.v1"); if (stored) { const parsed = JSON.parse(stored) as unknown; if (isWorkspaceState(parsed)) setWorkspace({ ...initialWorkspace, ...parsed, tasks: parsed.tasks.map(hydrateTask), activePriority: parsed.activePriority ?? "all", activeTag: parsed.activeTag }); } } finally { setReady(true); } }; void restore(); }, []);
  useEffect(() => { if (ready) void AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(workspace)); }, [ready, workspace]);
  const toggleTask = useCallback((taskId: string) => setWorkspace((current) => { const source = current.tasks.find((task) => task.id === taskId); if (!source) return current; const completing = !source.completed; const next = completing ? makeNextTask(source) : null; const sourceId = source.recurrenceSourceId ?? source.id; const hasNext = next ? current.tasks.some((task) => task.recurrenceSourceId === sourceId && task.dueDate === next.dueDate) : false; return { ...current, tasks: [...current.tasks.map((task) => task.id === taskId ? { ...task, completed: completing, completedAt: completing ? new Date().toISOString() : undefined } : task), ...(next && !hasNext ? [next] : [])] }; }), []);
  const addTask = useCallback((draft: NewTask) => { const title = draft.title.trim(); if (!title) return; setWorkspace((current) => ({ ...current, tasks: [{ id: `task-${Date.now()}`, title, projectId: draft.projectId, dueDate: draft.dueDate, priority: draft.priority, tags: normalizeTags(draft.tags), recurrence: draft.recurrence, reminderAt: draft.reminderAt, completed: false, createdAt: new Date().toISOString() }, ...current.tasks] })); }, []);
  const addProject = useCallback((draft: NewProject) => { const name = draft.name.trim(); if (!name) return; setWorkspace((current) => ({ ...current, projects: [...current.projects, { id: `project-${Date.now()}`, name, description: draft.description.trim() || "A focused body of work.", color: projectColors[current.projects.length % projectColors.length], status: "active", createdAt: new Date().toISOString() }] })); }, []);
  const setActiveDate = useCallback((activeDate: string) => setWorkspace((current) => ({ ...current, activeDate })), []);
  const setThemeMode = useCallback((themeMode: ThemeMode) => setWorkspace((current) => ({ ...current, themeMode })), []);
  const setMotionMode = useCallback((motionMode: MotionMode) => setWorkspace((current) => ({ ...current, motionMode })), []);
  const setFilters = useCallback((activePriority: TaskPriority | "all", activeTag?: string) => setWorkspace((current) => ({ ...current, activePriority, activeTag })), []);
  const setTaskNotificationId = useCallback((taskId: string, notificationId?: string) => setWorkspace((current) => ({ ...current, tasks: current.tasks.map((task) => task.id === taskId ? { ...task, notificationId } : task) })), []);
  const resetWorkspace = useCallback(() => { void AsyncStorage.multiRemove([STORAGE_KEY, "lumen.workspace.v1"]); setWorkspace(initialWorkspace); }, []);
  const value = useMemo<LumenWorkspace>(() => ({ ...workspace, ready, activePriority: workspace.activePriority ?? "all", palette: lumenPalettes[workspace.themeMode], toggleTask, addTask, addProject, setActiveDate, setThemeMode, setMotionMode, setFilters, setTaskNotificationId, resetWorkspace, tasksForDate: (dateKey) => workspace.tasks.filter((task) => task.dueDate === dateKey).map(hydrateTask).sort(compareTasks), tasksForProject: (projectId) => workspace.tasks.filter((task) => task.projectId === projectId).map(hydrateTask).sort(compareTasks), projectForTask: (projectId) => workspace.projects.find((project) => project.id === projectId), allTags: [...new Set(workspace.tasks.flatMap((task) => task.tags ?? []))].sort() }), [workspace, ready, toggleTask, addTask, addProject, setActiveDate, setThemeMode, setMotionMode, setFilters, setTaskNotificationId, resetWorkspace]);
  return <WorkspaceContext.Provider value={value}>{children}</WorkspaceContext.Provider>;
}
export function useLumen() { const workspace = useContext(WorkspaceContext); if (!workspace) throw new Error("useLumen must be used within LumenWorkspaceProvider"); return workspace; }
