export const JOB_ORDER_PHASES = ["PLANNING", "DESIGN", "PROCUREMENT", "EXECUTION", "QA_INSPECTION", "PUNCH_LIST", "CLIENT_SIGNOFF", "COMPLETED"] as const;
export const JOB_ORDER_PHASE_LABELS: Record<JobOrderPhase, string> = { PLANNING: "Planning", DESIGN: "Design", PROCUREMENT: "Procurement", EXECUTION: "Execution", QA_INSPECTION: "QA / inspection", PUNCH_LIST: "Punch list", CLIENT_SIGNOFF: "Client sign-off", ON_HOLD: "On hold", COMPLETED: "Completed", CANCELLED: "Cancelled" };
export const DISCIPLINES = ["CIVIL_STRUCTURAL", "MECHANICAL", "ELECTRICAL", "PROCESS_INSTRUMENTATION", "ENVIRONMENTAL", "PROJECT_MANAGEMENT", "QUALITY_SAFETY"] as const;
export const DISCIPLINE_LABELS: Record<EngineeringDiscipline, string> = { CIVIL_STRUCTURAL: "Civil / structural", MECHANICAL: "Mechanical", ELECTRICAL: "Electrical", PROCESS_INSTRUMENTATION: "Process / instrumentation", ENVIRONMENTAL: "Environmental", PROJECT_MANAGEMENT: "Project management", QUALITY_SAFETY: "Quality / safety" };
export const WORK_PACKAGE_STATUSES = ["NOT_STARTED", "IN_PROGRESS", "BLOCKED", "UNDER_REVIEW", "COMPLETED"] as const;
export const WORK_PACKAGE_STATUS_LABELS: Record<WorkPackageStatus, string> = { NOT_STARTED: "Not started", IN_PROGRESS: "In progress", BLOCKED: "Blocked", UNDER_REVIEW: "Under review", COMPLETED: "Completed" };

export type JobOrderPhase = "PLANNING" | "DESIGN" | "PROCUREMENT" | "EXECUTION" | "QA_INSPECTION" | "PUNCH_LIST" | "CLIENT_SIGNOFF" | "ON_HOLD" | "COMPLETED" | "CANCELLED";
export type EngineeringDiscipline = typeof DISCIPLINES[number];
export type WorkPackageStatus = typeof WORK_PACKAGE_STATUSES[number];
export type JobOrderPriority = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type BudgetAlertStatus = "ON_TRACK" | "WATCH" | "AT_RISK" | "OVER_BUDGET";
export type CostDocumentType = "SUBCONTRACTOR_INVOICE" | "PURCHASE_RECEIPT" | "CONTRACT" | "CHANGE_ORDER" | "OTHER";
export const COST_DOCUMENT_APPROVAL_STATUSES = ["PENDING", "APPROVED"] as const;
export type CostDocumentApprovalStatus = typeof COST_DOCUMENT_APPROVAL_STATUSES[number];
export const COST_DOCUMENT_APPROVAL_LABELS: Record<CostDocumentApprovalStatus, string> = { PENDING: "Pending approval", APPROVED: "Approved" };
export const COST_DOCUMENT_CATEGORY_TAGS = ["Invoice", "Receipt", "Contract", "Change order", "Compliance", "Vendor quote"] as const;
export function costDocumentCategoryTags(documentType: CostDocumentType): string[] { return documentType === "SUBCONTRACTOR_INVOICE" ? ["Invoice"] : documentType === "PURCHASE_RECEIPT" ? ["Receipt"] : documentType === "CONTRACT" ? ["Contract"] : documentType === "CHANGE_ORDER" ? ["Change order"] : []; }
export const COST_DOCUMENT_PENDING_WARNING_HOURS = 48;
export function pendingApprovalAgeHours(document: CostDocument, now = new Date()) {
  if ((document.approvalStatus ?? "PENDING") !== "PENDING") return 0;
  const latestPendingDecision = [...(document.approvalHistory ?? [])].sort((a, b) => b.changedAt.localeCompare(a.changedAt)).find((entry) => entry.status === "PENDING");
  const pendingSince = Date.parse(latestPendingDecision?.changedAt ?? document.uploadedAt);
  return Number.isFinite(pendingSince) ? Math.max(0, Math.floor((now.getTime() - pendingSince) / (60 * 60 * 1000))) : 0;
}
export function isCostDocumentApprovalOverdue(document: CostDocument, now = new Date()) { return pendingApprovalAgeHours(document, now) > COST_DOCUMENT_PENDING_WARNING_HOURS; }
export function pendingApprovalAgeLabel(hours: number) { return hours >= 48 ? `${Math.floor(hours / 24)}D ${hours % 24}H` : `${hours}H`; }
export type CostDocumentApprovalHistoryEntry = { id: string; status: CostDocumentApprovalStatus; reviewNote?: string; changedAt: string; changedBy: string };
export type PmecRegion = "EGYPT" | "ARUBA" | "VENEZUELA" | "PANAMA" | "OTHER";

export type CostLineItem = { name: string; quantity: number; unit: string; unitCost: number };
export type WorkPackageTask = { id: string; title: string; description: string; discipline: EngineeringDiscipline; status: WorkPackageStatus; progress: number; assignedTo: string; laborCost: number; materialCost: number; materials: CostLineItem[]; startDate?: string; dueDate?: string; completedDate?: string; notes?: string; wbsPhase?: string };
export type JobOrderMilestone = { id: string; label: string; targetDate: string; achieved: boolean; achievedDate?: string };
export type CostDocument = { id: string; url: string; description: string; documentType: CostDocumentType; approvalStatus?: CostDocumentApprovalStatus; reviewNote?: string; approvalHistory?: CostDocumentApprovalHistoryEntry[]; tags?: string[]; amount?: number; uploadedAt: string; uploadedBy: string; fileName?: string; mimeType?: string; sizeBytes?: number };
export type JobOrder = { id: string; title: string; description: string; clientName: string; discipline: EngineeringDiscipline; phase: JobOrderPhase; priority: JobOrderPriority; currency: string; budget: number; contingencyPct: number; quotationId?: string; netLaborMultiplier?: number; subcontractorName?: string; projectManagerName: string; region: PmecRegion; startDate: string; targetEndDate: string; actualEndDate?: string; clientApprovalDate?: string; clientApprovedBy?: string; tasks: WorkPackageTask[]; milestones: JobOrderMilestone[]; costDocuments: CostDocument[]; createdAt: string; updatedAt: string; tags: string[] };
export type NewJobOrder = Pick<JobOrder, "title" | "description" | "clientName" | "discipline" | "priority" | "currency" | "budget" | "contingencyPct" | "projectManagerName" | "region" | "startDate" | "targetEndDate" | "subcontractorName" | "quotationId" | "tags">;

const stamp = "2026-08-24T09:00:00.000Z";
const task = (data: Omit<WorkPackageTask, "materialCost"> & { materialCost?: number }): WorkPackageTask => ({ ...data, materialCost: data.materials.length ? data.materials.reduce((sum, item) => sum + lineItemTotal(item), 0) : data.materialCost ?? 0 });

export const initialPmeJobOrders: JobOrder[] = [
  {
    id: "jo-coastal-substation", title: "Coastal Substation Electrical Retrofit", description: "Retrofit of a 13.8 kV coastal substation switchgear and protection relays, including SCADA integration and final commissioning.", clientName: "WEB Aruba N.V.", discipline: "ELECTRICAL", phase: "EXECUTION", priority: "HIGH", currency: "AWG", budget: 185000, contingencyPct: 12, quotationId: "Q-2025-118", netLaborMultiplier: 3.1, subcontractorName: "ELMAR N.V.", projectManagerName: "Aaron Croes", region: "ARUBA", startDate: "2026-02-01", targetEndDate: "2026-07-31", clientApprovalDate: "2025-12-05", clientApprovedBy: "Frank Tisellano", tags: ["electrical", "substation", "capital"], createdAt: stamp, updatedAt: stamp,
    milestones: [{ id: "m1", label: "Client approval", targetDate: "2025-12-05", achieved: true, achievedDate: "2025-12-05" }, { id: "m2", label: "Switchgear order placed", targetDate: "2026-02-15", achieved: true, achievedDate: "2026-02-18" }, { id: "m3", label: "Switchgear delivered", targetDate: "2026-04-15", achieved: false }, { id: "m4", label: "Installation complete", targetDate: "2026-06-30", achieved: false }, { id: "m5", label: "Commissioning & client sign-off", targetDate: "2026-07-25", achieved: false }],
    tasks: [task({ id: "coastal-1", title: "Site survey & as-built verification", description: "Field survey of existing switchgear, cable routing, and protection relay settings.", discipline: "ELECTRICAL", status: "COMPLETED", progress: 100, assignedTo: "ELMAR N.V.", laborCost: 6200, materials: [], startDate: "2026-02-01", dueDate: "2026-02-12", completedDate: "2026-02-10", notes: "Four circuits corrected against the as-built drawings.", wbsPhase: "01 — Site investigation & design" }), task({ id: "coastal-2", title: "Switchgear & relay procurement", description: "Procure replacement cubicles, relays, and control cable for the retrofit.", discipline: "ELECTRICAL", status: "IN_PROGRESS", progress: 60, assignedTo: "ELMAR N.V.", laborCost: 3500, materials: [{ name: "13.8kV switchgear cubicle", quantity: 4, unit: "ea", unitCost: 18500 }, { name: "Microprocessor protection relay", quantity: 6, unit: "ea", unitCost: 3000 }, { name: "Control cable", quantity: 400, unit: "m", unitCost: 8.75 }], startDate: "2026-02-15", dueDate: "2026-05-01", notes: "Factory acceptance test scheduled for April 20.", wbsPhase: "02 — Procurement" }), task({ id: "coastal-3", title: "Switchgear installation & termination", description: "Install new switchgear cubicles and terminate control and power cabling.", discipline: "ELECTRICAL", status: "NOT_STARTED", progress: 0, assignedTo: "ELMAR N.V.", laborCost: 24000, materials: [{ name: "Cable lugs & terminations", quantity: 120, unit: "ea", unitCost: 65 }, { name: "Termination kits", quantity: 8, unit: "kit", unitCost: 340 }], startDate: "2026-05-04", dueDate: "2026-06-26", wbsPhase: "03 — Installation" }), task({ id: "coastal-4", title: "Commissioning, relay testing & handover", description: "Complete relay testing, SCADA verification, energization, and client walkthrough.", discipline: "ELECTRICAL", status: "NOT_STARTED", progress: 0, assignedTo: "PMEC commissioning team", laborCost: 9800, materials: [], startDate: "2026-06-29", dueDate: "2026-07-25", wbsPhase: "04 — Commissioning & handover" })],
    costDocuments: [{ id: "doc-1", url: "local://cost-documents/substation-switchgear-po", description: "Switchgear Purchase Order — ELMAR N.V.", documentType: "PURCHASE_RECEIPT", approvalStatus: "APPROVED", tags: ["Receipt", "Compliance"], amount: 98000, uploadedAt: stamp, uploadedBy: "Aaron Croes" }],
  },
  {
    id: "jo-water-treatment", title: "Municipal Water Treatment Plant Upgrade — Phase II", description: "Detailed design for capacity expansion of the secondary treatment train, including instrumentation and updated process control networks.", clientName: "Greater Cairo Water & Sanitation Authority", discipline: "PROCESS_INSTRUMENTATION", phase: "DESIGN", priority: "CRITICAL", currency: "EGP", budget: 4200000, contingencyPct: 15, quotationId: "Q-2025-142", netLaborMultiplier: 3.2, projectManagerName: "Nour El-Sayed", region: "EGYPT", startDate: "2026-01-15", targetEndDate: "2026-12-20", tags: ["water-treatment", "municipal", "phase-2"], createdAt: stamp, updatedAt: stamp,
    milestones: [{ id: "m1", label: "Contract kickoff", targetDate: "2026-01-15", achieved: true, achievedDate: "2026-01-15" }, { id: "m2", label: "30% design review", targetDate: "2026-05-01", achieved: false }, { id: "m3", label: "HAZOP complete", targetDate: "2026-07-15", achieved: false }, { id: "m4", label: "Issued for construction", targetDate: "2026-11-30", achieved: false }],
    tasks: [task({ id: "water-1", title: "Hydraulic modeling of expanded train", description: "Model the proposed secondary treatment expansion and confirm pump sizing.", discipline: "PROCESS_INSTRUMENTATION", status: "COMPLETED", progress: 100, assignedTo: "Nour El-Sayed", laborCost: 145000, materials: [], startDate: "2026-01-15", dueDate: "2026-02-28", completedDate: "2026-02-25", notes: "Head margin confirmed for initial scope.", wbsPhase: "01 — Process design" }), task({ id: "water-2", title: "Instrumentation & control philosophy", description: "Define instrumentation list, control narrative, and SCADA integration approach.", discipline: "PROCESS_INSTRUMENTATION", status: "IN_PROGRESS", progress: 45, assignedTo: "Karim Fathy", laborCost: 120000, materials: [], startDate: "2026-03-01", dueDate: "2026-05-20", notes: "Draft control narrative circulated for QA review.", wbsPhase: "02 — Instrumentation & controls" }), task({ id: "water-3", title: "P&ID development — issue for review", description: "Develop piping and instrumentation diagrams for expanded train.", discipline: "PROCESS_INSTRUMENTATION", status: "NOT_STARTED", progress: 0, assignedTo: "TBD", laborCost: 260000, materials: [], startDate: "2026-05-21", dueDate: "2026-07-01", wbsPhase: "02 — Instrumentation & controls" }), task({ id: "water-4", title: "HAZOP workshop & action close-out", description: "Facilitate HAZOP workshop with client and safety representatives.", discipline: "QUALITY_SAFETY", status: "NOT_STARTED", progress: 0, assignedTo: "Quality / safety lead", laborCost: 80000, materials: [{ name: "Workshop facilitation & venue", quantity: 1, unit: "lot", unitCost: 120000 }], startDate: "2026-07-05", dueDate: "2026-07-15", wbsPhase: "03 — Safety review" })], costDocuments: [],
  },
  {
    id: "jo-hospital-wing", title: "Hospital Wing Structural Assessment & Seismic Retrofit", description: "Structural assessment and seismic retrofit of an active hospital wing, including column jacketing, shear walls, and final recertification.", clientName: "Hospital Punta Pacífica Group", discipline: "CIVIL_STRUCTURAL", phase: "QA_INSPECTION", priority: "HIGH", currency: "USD", budget: 310000, contingencyPct: 10, quotationId: "Q-2025-076", netLaborMultiplier: 3.1, subcontractorName: "Estructuras del Istmo S.A.", projectManagerName: "Luis Herrera", region: "PANAMA", startDate: "2025-09-01", targetEndDate: "2026-05-15", clientApprovalDate: "2025-08-15", clientApprovedBy: "Dr. Elena Vasquez", tags: ["structural", "hospital", "critical-facility"], createdAt: stamp, updatedAt: stamp,
    milestones: [{ id: "m1", label: "Assessment report approved", targetDate: "2025-10-15", achieved: true, achievedDate: "2025-10-15" }, { id: "m2", label: "Retrofit design approved", targetDate: "2025-12-15", achieved: true, achievedDate: "2025-12-19" }, { id: "m3", label: "Construction complete", targetDate: "2026-02-28", achieved: true, achievedDate: "2026-03-05" }, { id: "m4", label: "Shear wall performance test", targetDate: "2026-04-10", achieved: true, achievedDate: "2026-04-12" }, { id: "m5", label: "Structural recertification", targetDate: "2026-05-15", achieved: false }],
    tasks: [task({ id: "hospital-1", title: "Structural condition assessment", description: "Visual and non-destructive assessment of the active wing.", discipline: "CIVIL_STRUCTURAL", status: "COMPLETED", progress: 100, assignedTo: "Luis Herrera", laborCost: 32000, materials: [{ name: "Rebar scanning & NDT services", quantity: 1, unit: "lot", unitCost: 4500 }], startDate: "2025-09-01", dueDate: "2025-10-18", completedDate: "2025-10-18", wbsPhase: "01 — Assessment" }), task({ id: "hospital-2", title: "Retrofit design — column jacketing & shear walls", description: "Design reinforced concrete column jacketing and new shear walls.", discipline: "CIVIL_STRUCTURAL", status: "COMPLETED", progress: 100, assignedTo: "Luis Herrera", laborCost: 58000, materials: [], startDate: "2025-10-20", dueDate: "2025-12-15", completedDate: "2025-12-19", wbsPhase: "01 — Assessment" }), task({ id: "hospital-3", title: "Column jacketing construction", description: "Construct reinforced concrete jacketing across 18 identified columns.", discipline: "CIVIL_STRUCTURAL", status: "COMPLETED", progress: 100, assignedTo: "Estructuras del Istmo S.A.", laborCost: 62000, materials: [{ name: "Ready-mix concrete", quantity: 65, unit: "m³", unitCost: 195 }, { name: "Reinforcement steel", quantity: 8500, unit: "kg", unitCost: 1.6 }, { name: "Formwork rental", quantity: 1, unit: "lot", unitCost: 12500 }], startDate: "2026-01-05", dueDate: "2026-03-01", completedDate: "2026-03-05", wbsPhase: "02 — Construction" }), task({ id: "hospital-4", title: "New shear wall construction", description: "Construct two reinforced concrete shear walls at stairwells.", discipline: "CIVIL_STRUCTURAL", status: "COMPLETED", progress: 100, assignedTo: "Estructuras del Istmo S.A.", laborCost: 41000, materials: [{ name: "Ready-mix concrete", quantity: 38, unit: "m³", unitCost: 195 }, { name: "Reinforcement steel", quantity: 6200, unit: "kg", unitCost: 1.6 }], startDate: "2026-03-08", dueDate: "2026-04-10", completedDate: "2026-04-12", wbsPhase: "02 — Construction" }), task({ id: "hospital-5", title: "Structural re-certification & final report", description: "Complete inspection, load testing, and updated seismic certification.", discipline: "QUALITY_SAFETY", status: "UNDER_REVIEW", progress: 88, assignedTo: "Luis Herrera", laborCost: 18500, materials: [{ name: "Third-party inspection fee", quantity: 1, unit: "lot", unitCost: 3200 }], startDate: "2026-04-14", dueDate: "2026-05-10", notes: "Inspection complete; awaiting final signed certificate.", wbsPhase: "03 — Re-certification" })], costDocuments: [{ id: "doc-2", url: "local://cost-documents/hospital-concrete", description: "Concrete supply receipt — March 2026", documentType: "PURCHASE_RECEIPT", approvalStatus: "PENDING", tags: ["Receipt", "Invoice"], amount: 20115, uploadedAt: stamp, uploadedBy: "Luis Herrera" }],
  },
];

export function lineItemTotal(item: CostLineItem) { return item.quantity * item.unitCost; }
export function taskTotalCost(taskItem: WorkPackageTask) { return taskItem.laborCost + taskItem.materialCost; }
export function jobOrderProgress(job: JobOrder) { return job.tasks.length ? Math.round(job.tasks.reduce((sum, item) => sum + item.progress, 0) / job.tasks.length) : 0; }
export function jobOrderSpent(job: JobOrder) { return job.tasks.reduce((sum, item) => sum + taskTotalCost(item), 0); }
export function contingencyAmount(job: JobOrder) { return Math.round(job.budget * job.contingencyPct / 100); }
export function totalAuthorized(job: JobOrder) { return job.budget + contingencyAmount(job); }
export function actualSpentPctOfBudget(job: JobOrder) { return job.budget ? Math.round(jobOrderSpent(job) / job.budget * 100) : 0; }
export function spentPctOfBudget(job: JobOrder) { return Math.min(actualSpentPctOfBudget(job), 100); }
export function remainingAuthorized(job: JobOrder) { return Math.max(0, totalAuthorized(job) - jobOrderSpent(job)); }
export function isOverBudget(job: JobOrder) { return jobOrderSpent(job) > job.budget; }
export const BUDGET_ALERT_LABELS: Record<BudgetAlertStatus, string> = { ON_TRACK: "On track", WATCH: "Budget watch", AT_RISK: "Budget at risk", OVER_BUDGET: "Over budget" };
export function budgetAlertStatus(job: JobOrder): BudgetAlertStatus { const burn = actualSpentPctOfBudget(job); return burn > 100 ? "OVER_BUDGET" : burn >= 90 ? "AT_RISK" : burn >= 75 ? "WATCH" : "ON_TRACK"; }
export function budgetVariance(job: JobOrder) { return jobOrderSpent(job) - job.budget; }
export function matchesProjectSearch(job: JobOrder, query: string) { const normalized = query.trim().toLocaleLowerCase(); if (!normalized) return true; return [job.title, job.clientName, job.projectManagerName, job.region, job.discipline, job.phase, ...job.tags].join(" ").toLocaleLowerCase().includes(normalized); }
export function completedTaskCount(job: JobOrder) { return job.tasks.filter((item) => item.status === "COMPLETED").length; }
export function impliedLaborMultiplier(job: JobOrder) { const laborSpent = job.tasks.reduce((sum, item) => sum + item.laborCost, 0); return laborSpent && job.budget ? Math.round(job.budget / laborSpent * 100) / 100 : null; }
export function formatMoney(currency: string, value: number) { return `${currency} ${Math.round(value).toLocaleString("en-US")}`; }
export function groupCurrencyTotals(jobs: JobOrder[], value: (job: JobOrder) => number) { return Object.entries(jobs.reduce<Record<string, number>>((result, job) => ({ ...result, [job.currency]: (result[job.currency] ?? 0) + value(job) }), {})).map(([currency, total]) => ({ currency, total })); }
export function nextJobOrderPhase(phase: JobOrderPhase): JobOrderPhase | null { const index = JOB_ORDER_PHASES.indexOf(phase as typeof JOB_ORDER_PHASES[number]); return index >= 0 && index < JOB_ORDER_PHASES.length - 1 ? JOB_ORDER_PHASES[index + 1] : null; }
export function groupWorkPackages(job: JobOrder) { return Object.entries(job.tasks.reduce<Record<string, WorkPackageTask[]>>((groups, item) => ({ ...groups, [item.wbsPhase ?? "General"]: [...(groups[item.wbsPhase ?? "General"] ?? []), item] }), {})); }
