import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, type PropsWithChildren, useCallback, useContext, useEffect, useMemo, useState } from "react";

import { usePmecJobOrders } from "@/lib/pmec-job-order-workspace";
import { usePmecDeliverySync } from "@/lib/pmec-delivery-sync";
import type { SharedAssignment } from "@/lib/pmec-delivery-sync";

export type PmecWorkforcePerson = { id: string; name: string; role: string; discipline: string; type: "Employee" | "Contractor"; location: string; status: "Active" | "Away" | "Pending"; allocation: number; weeklyCapacity: number; employment: string };
export type PmecTimeLog = { id: string; employeeId: string; jobOrderId: string; taskId: string; date: string; hours: number; note: string; status: "Submitted" | "Approved"; synced?: boolean };
export type PmecLeaveRequest = { id: string; employeeId: string; type: "Vacation" | "Sick" | "Personal"; startDate: string; endDate: string; workDays: number; status: "pending" | "approved" | "rejected"; note?: string };
export type TaskAssignment = { id: string; jobOrderId: string; taskId: string; employeeId: string; assignedAt: string };

const STORAGE_KEY = "lumen.pmec.control-center.v1";
const staffSeeds = [
  ["emp-01", "Aaron Croes", "Project Director", "Project Management", "Aruba", 88], ["emp-02", "Nour El-Sayed", "Senior Process Engineer", "Process / Instrumentation", "Cairo", 82], ["emp-03", "Luis Herrera", "Civil Structural Lead", "Civil / Structural", "Panama", 91], ["emp-04", "Karim Fathy", "Control Systems Engineer", "Process / Instrumentation", "Cairo", 76], ["emp-05", "Sofia Arends", "Electrical Engineer", "Electrical", "Aruba", 84], ["emp-06", "Daniel Geerman", "QA / HSE Lead", "Quality / Safety", "Aruba", 72], ["emp-07", "Amelia Ruiz", "Project Coordinator", "Project Management", "Panama", 68], ["emp-08", "Mila Tromp", "Planner", "Project Management", "Aruba", 64], ["emp-09", "Noah Croes", "Electrical Technician", "Electrical", "Aruba", 92], ["emp-10", "Iris Peterson", "Mechanical Engineer", "Mechanical", "Aruba", 78], ["emp-11", "Owen De Cuba", "Safety Officer", "Quality / Safety", "Aruba", 70], ["emp-12", "Nora Kock", "Quantity Surveyor", "Project Management", "Aruba", 66], ["emp-13", "Levi Lacle", "Site Engineer", "Civil / Structural", "Aruba", 86], ["emp-14", "Ella Thijsen", "QA Specialist", "Quality / Safety", "Aruba", 74], ["emp-15", "Mason Croes", "Procurement Engineer", "Electrical", "Aruba", 89], ["emp-16", "Lina Loefstok", "Mechanical Technician", "Mechanical", "Aruba", 60], ["emp-17", "Julian Koolman", "Field Supervisor", "Project Management", "Aruba", 80], ["emp-18", "Mia Eman", "Instrumentation Engineer", "Process / Instrumentation", "Cairo", 77], ["emp-19", "Theo Nichols", "Design Engineer", "Electrical", "Aruba", 63], ["emp-20", "Sara Doran", "Civil Engineer", "Civil / Structural", "Panama", 83], ["emp-21", "Jade Figaroa", "Document Controller", "Project Management", "Aruba", 56], ["emp-22", "Victor Quant", "Mechanical Lead", "Mechanical", "Aruba", 87], ["emp-23", "Olivia Maduro", "Electrical Designer", "Electrical", "Aruba", 71], ["emp-24", "Henry Peterson", "HSE Coordinator", "Quality / Safety", "Aruba", 69], ["emp-25", "Ava Arends", "Project Engineer", "Project Management", "Aruba", 90], ["emp-26", "Gabriel Lacle", "Structural Engineer", "Civil / Structural", "Panama", 75], ["emp-27", "Eva Tromp", "Junior Planner", "Project Management", "Aruba", 58], ["employee-76", "Percy Solagnier", "Mechanical Engineer", "Mechanical", "Aruba", 73],
] as const;
const contractorSeeds = [["con-01", "ELMAR N.V.", "Electrical Subcontractor", "Electrical", "Aruba", 82], ["con-02", "Estructuras del Istmo S.A.", "Structural Subcontractor", "Civil / Structural", "Panama", 85], ["con-03", "Nile Controls LLC", "Controls Contractor", "Process / Instrumentation", "Cairo", 61], ["con-04", "Coastline HVAC", "Mechanical Subcontractor", "Mechanical", "Aruba", 52], ["con-05", "Island Scaffolding", "Access Contractor", "Quality / Safety", "Aruba", 48], ["con-06", "Terra Solar", "Electrical Specialist", "Electrical", "Aruba", 66]] as const;
const workforce: PmecWorkforcePerson[] = [...staffSeeds.map(([id, name, role, discipline, location, allocation], index) => ({ id, name, role, discipline, location, allocation, type: "Employee" as const, weeklyCapacity: 40, employment: "PMEC employee", status: index === 7 ? "Away" as const : index === 20 ? "Pending" as const : "Active" as const })), ...contractorSeeds.map(([id, name, role, discipline, location, allocation]) => ({ id, name, role, discipline, location, allocation, type: "Contractor" as const, weeklyCapacity: 40, employment: "External specialist", status: "Active" as const }))];
const initialAssignments: TaskAssignment[] = [{ id: "assign-1", jobOrderId: "jo-coastal-substation", taskId: "coastal-2", employeeId: "emp-05", assignedAt: "2026-04-01" }, { id: "assign-2", jobOrderId: "jo-water-treatment", taskId: "water-2", employeeId: "emp-04", assignedAt: "2026-04-02" }, { id: "assign-3", jobOrderId: "jo-hospital-wing", taskId: "hospital-5", employeeId: "emp-03", assignedAt: "2026-04-05" }];
const initialLogs: PmecTimeLog[] = [{ id: "log-1", employeeId: "emp-05", jobOrderId: "jo-coastal-substation", taskId: "coastal-2", date: "2026-04-20", hours: 8, note: "Factory acceptance test coordination", status: "Approved" }, { id: "log-2", employeeId: "emp-09", jobOrderId: "jo-coastal-substation", taskId: "coastal-2", date: "2026-04-21", hours: 7.5, note: "Relay configuration review", status: "Submitted" }, { id: "log-3", employeeId: "emp-04", jobOrderId: "jo-water-treatment", taskId: "water-2", date: "2026-04-20", hours: 8, note: "Control narrative drafting", status: "Approved" }, { id: "log-4", employeeId: "emp-02", jobOrderId: "jo-water-treatment", taskId: "water-2", date: "2026-04-21", hours: 6, note: "Client design workshop", status: "Approved" }, { id: "log-5", employeeId: "emp-03", jobOrderId: "jo-hospital-wing", taskId: "hospital-5", date: "2026-04-21", hours: 7, note: "Certification review with inspector", status: "Submitted" }, { id: "log-6", employeeId: "emp-06", jobOrderId: "jo-hospital-wing", taskId: "hospital-5", date: "2026-04-21", hours: 4, note: "QA evidence reconciliation", status: "Approved" }];
const initialLeave: PmecLeaveRequest[] = [{ id: "leave-1", employeeId: "emp-08", type: "Vacation", startDate: "2026-05-11", endDate: "2026-05-15", workDays: 5, status: "pending" }, { id: "leave-2", employeeId: "emp-05", type: "Personal", startDate: "2026-04-28", endDate: "2026-04-28", workDays: 1, status: "pending" }, { id: "leave-3", employeeId: "emp-13", type: "Sick", startDate: "2026-04-17", endDate: "2026-04-18", workDays: 1, status: "approved", note: "Recorded by HR" }];

type ControlState = { assignments: TaskAssignment[]; timeLogs: PmecTimeLog[]; leaveRequests: PmecLeaveRequest[] };
type ControlContextValue = ControlState & { ready: boolean; deliverySyncState: "live" | "demo"; workforce: PmecWorkforcePerson[]; sharedAssignments: SharedAssignment[]; assignTask: (jobOrderId: string, taskId: string, employeeId: string) => void; addTimeLog: (input: Omit<PmecTimeLog, "id" | "status">) => void; approveTimeLog: (id: string) => void; reviewLeave: (id: string, status: "approved" | "rejected", note?: string) => void; resetControlDemo: () => void };
const ControlContext = createContext<ControlContextValue | null>(null);
const initialState: ControlState = { assignments: initialAssignments, timeLogs: initialLogs, leaveRequests: initialLeave };

export function PmecControlWorkspaceProvider({ children }: PropsWithChildren) {
  const { jobOrders, updateTask } = usePmecJobOrders();
  const shared = usePmecDeliverySync();
  const [state, setState] = useState<ControlState>(initialState);
  const [ready, setReady] = useState(false);
  useEffect(() => { void AsyncStorage.getItem(STORAGE_KEY).then((stored) => { if (stored) { try { const parsed = JSON.parse(stored) as ControlState; if (Array.isArray(parsed.assignments) && Array.isArray(parsed.timeLogs) && Array.isArray(parsed.leaveRequests)) setState(parsed); } catch { /* retain seed state */ } } }).finally(() => setReady(true)); }, []);
  useEffect(() => { if (ready) void AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [ready, state]);
  const syncedAssignments = shared.allAssignments.map((item) => ({ id: item.id, jobOrderId: item.jobOrderId, taskId: item.taskId, employeeId: item.employeeId, assignedAt: item.dueDate ?? new Date().toISOString().slice(0, 10) }));
  const syncedTimeLogs = shared.allTimeLogs.map((item) => ({ id: item.id, employeeId: item.employeeId, jobOrderId: item.jobOrderId, taskId: item.taskId, date: item.workDate, hours: item.minutes / 60, note: item.note, status: item.status === "approved" ? "Approved" as const : "Submitted" as const, synced: true }));
  const deliverySyncState = shared.managerSyncState === "live" ? "live" as const : "demo" as const;
  const assignments = [...syncedAssignments, ...state.assignments.filter((item) => !syncedAssignments.some((remote) => remote.jobOrderId === item.jobOrderId && remote.taskId === item.taskId))];
  const timeLogs = [...syncedTimeLogs, ...state.timeLogs.filter((item) => !syncedTimeLogs.some((remote) => remote.id === item.id))];
  const assignTask = useCallback((jobOrderId: string, taskId: string, employeeId: string) => { const person = workforce.find((item) => item.id === employeeId); const jobOrder = jobOrders.find((item) => item.id === jobOrderId); const task = jobOrder?.tasks.find((item) => item.id === taskId); if (!person || !jobOrder || !task) return; updateTask(jobOrderId, taskId, { assignedTo: person.name }); void shared.assign({ jobOrderId, jobOrderTitle: jobOrder.title, taskId, taskTitle: task.title, employeeId, employeeName: person.name, discipline: person.discipline, status: task.progress >= 100 ? "complete" : task.progress > 0 ? "in_progress" : "assigned", progress: task.progress, assignedBy: "Aaron Croes", dueDate: jobOrder.targetEndDate }); setState((current) => ({ ...current, assignments: [...current.assignments.filter((item) => item.taskId !== taskId || item.jobOrderId !== jobOrderId), { id: `assignment-${Date.now()}`, jobOrderId, taskId, employeeId, assignedAt: new Date().toISOString().slice(0, 10) }] })); }, [jobOrders, shared, updateTask]);
  const addTimeLog = useCallback((input: Omit<PmecTimeLog, "id" | "status">) => { const assignment = assignments.find((item) => item.employeeId === input.employeeId && item.jobOrderId === input.jobOrderId && item.taskId === input.taskId); const person = workforce.find((item) => item.id === input.employeeId); if (assignment && person) void shared.submitTime({ assignmentId: assignment.id, jobOrderId: input.jobOrderId, taskId: input.taskId, workDate: input.date, minutes: Math.max(15, Math.round(input.hours * 60)), note: input.note }); setState((current) => ({ ...current, timeLogs: [{ ...input, id: `time-${Date.now()}`, status: "Submitted" }, ...current.timeLogs] })); }, [assignments, shared]);
  const approveTimeLog = useCallback((id: string) => { const remote = syncedTimeLogs.find((item) => item.id === id); if (remote) void shared.reviewTime(id, "approved", "Approved in PMEC Control Center"); setState((current) => ({ ...current, timeLogs: current.timeLogs.map((item) => item.id === id ? { ...item, status: "Approved" } : item) })); }, [shared, syncedTimeLogs]);
  const reviewLeave = useCallback((id: string, status: "approved" | "rejected", note?: string) => setState((current) => ({ ...current, leaveRequests: current.leaveRequests.map((item) => item.id === id ? { ...item, status, note: note?.trim() || item.note } : item) })), []);
  const resetControlDemo = useCallback(() => { void AsyncStorage.removeItem(STORAGE_KEY); setState(initialState); }, []);
  const value = useMemo<ControlContextValue>(() => ({ ...state, assignments, timeLogs, ready, deliverySyncState, workforce, sharedAssignments: shared.allAssignments, assignTask, addTimeLog, approveTimeLog, reviewLeave, resetControlDemo }), [state, assignments, timeLogs, ready, deliverySyncState, shared.allAssignments, assignTask, addTimeLog, approveTimeLog, reviewLeave, resetControlDemo]);
  return <ControlContext.Provider value={value}>{children}</ControlContext.Provider>;
}
export function usePmecControl() { const context = useContext(ControlContext); if (!context) throw new Error("usePmecControl must be used inside PmecControlWorkspaceProvider"); return context; }
