import { Redirect, Tabs } from "expo-router";
import { Platform, StyleSheet } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { HapticTab } from "@/components/haptic-tab";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useLumen } from "@/lib/lumen-workspace";
import { getPmecHostWorkspace } from "@/lib/pmec-host-routing";
export default function TabLayout() { const { palette } = useLumen(); const insets = useSafeAreaInsets(); const hostWorkspace = getPmecHostWorkspace(); const bottomPadding = Platform.OS === "web" ? 11 : Math.max(insets.bottom, 9); if (hostWorkspace === "hr" || hostWorkspace === "pm") return <Redirect href="/control-center" />; return <Tabs screenOptions={{ headerShown: false, tabBarActiveTintColor: palette.accent, tabBarInactiveTintColor: palette.muted, tabBarButton: HapticTab, tabBarHideOnKeyboard: true, tabBarLabelStyle: styles.label, tabBarStyle: { backgroundColor: palette.background, borderTopColor: palette.border, borderTopWidth: StyleSheet.hairlineWidth, height: 57 + bottomPadding, paddingBottom: bottomPadding, paddingTop: 7 } }}><Tabs.Screen name="index" options={{ title: "Home", tabBarIcon: ({ color }) => <IconSymbol color={color} name="checklist" size={21} /> }} /><Tabs.Screen name="work" options={{ title: "Work", tabBarIcon: ({ color }) => <IconSymbol color={color} name="calendar" size={21} /> }} /><Tabs.Screen name="projects" options={{ title: "Projects", tabBarIcon: ({ color }) => <IconSymbol color={color} name="folder.fill" size={21} /> }} /><Tabs.Screen name="pay" options={{ title: "Pay", tabBarIcon: ({ color }) => <IconSymbol color={color} name="creditcard.fill" size={21} /> }} /><Tabs.Screen name="settings" options={{ title: "Profile", tabBarIcon: ({ color }) => <IconSymbol color={color} name="gearshape.fill" size={21} /> }} /><Tabs.Screen name="calendar" options={{ href: null }} /><Tabs.Screen name="focus" options={{ href: null }} /></Tabs>; }
const styles = StyleSheet.create({ label: { fontSize: 10, fontWeight: "800", letterSpacing: 0.2, marginTop: 2 } });
