import { useMemo } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Redirect, useRouter } from "expo-router";
import Animated, { FadeInDown } from "react-native-reanimated";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useEss } from "@/lib/ess-workspace";
import { useLumen } from "@/lib/lumen-workspace";
import { formatDate } from "@/lib/lumen-utils";

export default function HomeScreen() { const router = useRouter(); const { employee, isAuthenticated, onboarded, projects, todayAttendance } = useEss(); const { palette, tasksForDate, activeDate } = useLumen(); const styles = useMemo(() => makeStyles(palette), [palette]); if (!onboarded) return <Redirect href="/ess/onboarding" />; if (!isAuthenticated) return <Redirect href="/ess/login" />; const tasks = tasksForDate(activeDate).filter((task) => !task.completed); const activeProject = projects.find((project) => project.id === todayAttendance?.projectId); const action = () => { haptic.light(); router.push("/attendance"); };
  return <ScreenContainer containerClassName={styles.container} edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Animated.View entering={FadeInDown.duration(260)} style={styles.hero}><Text style={styles.kicker}>{formatDate(activeDate).toUpperCase()}</Text><Text style={styles.title}>HELLO,{`\n`}{employee.firstName.toUpperCase()}.</Text><Text style={styles.role}>{employee.role} · {employee.department}</Text></Animated.View><Pressable accessibilityRole="button" onPress={action} style={({ pressed }) => [styles.attendance, pressed && styles.pressed]}><View><Text style={styles.cardKicker}>ATTENDANCE</Text><Text style={styles.attendanceTitle}>{todayAttendance?.clockIn && !todayAttendance.clockOut ? "YOU’RE CLOCKED IN." : todayAttendance?.clockOut ? "DAY COMPLETE." : "READY TO START?"}</Text><Text style={styles.attendanceMeta}>{activeProject ? activeProject.name : todayAttendance?.clockOut ? "Your time was saved locally." : "Choose a project and record your time."}</Text></View><Text style={styles.attendanceArrow}>{todayAttendance?.clockIn && !todayAttendance.clockOut ? "→" : "+"}</Text></Pressable><View style={styles.shortcutGrid}>{[{ label: "PROJECTS", sub: "Assigned work", route: "/(tabs)/projects" }, { label: "MY TASKS", sub: `${tasks.length} open today`, route: "/(tabs)/focus" }, { label: "CALENDAR", sub: "Plan your time", route: "/(tabs)/calendar" }, { label: "PAYSLIPS", sub: "View your pay", route: "/(tabs)/pay" }].map((item) => <Pressable key={item.label} onPress={() => router.push(item.route as never)} style={({ pressed }) => [styles.shortcut, pressed && styles.pressed]}><Text style={styles.shortcutLabel}>{item.label}</Text><Text style={styles.shortcutSub}>{item.sub}</Text><Text style={styles.shortcutArrow}>→</Text></Pressable>)}</View><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>TODAY’S PRIORITIES</Text><Pressable onPress={() => router.push("/(tabs)/focus")}><Text style={styles.viewAll}>OPEN TASKS</Text></Pressable></View>{tasks.slice(0, 3).map((task) => <View key={task.id} style={styles.taskRow}><View style={[styles.taskDot, { backgroundColor: task.priority === "high" ? palette.accent : palette.border }]} /><Text style={styles.taskTitle}>{task.title}</Text></View>)}</ScrollView></ScreenContainer>; }
const makeStyles = (palette: ReturnType<typeof useLumen>["palette"]) => StyleSheet.create({ container: { backgroundColor: palette.background }, content: { paddingBottom: 28 }, hero: { paddingHorizontal: 22, paddingTop: 18, paddingBottom: 26 }, kicker: { color: palette.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginBottom: 10 }, title: { color: palette.foreground, fontSize: 44, fontWeight: "900", letterSpacing: -2, lineHeight: 48 }, role: { color: palette.muted, fontSize: 13, fontWeight: "700", marginTop: 9 }, attendance: { backgroundColor: palette.foreground, flexDirection: "row", justifyContent: "space-between", marginHorizontal: 22, minHeight: 133, padding: 19 }, cardKicker: { color: palette.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, attendanceTitle: { color: palette.inverseText, fontSize: 23, fontWeight: "900", letterSpacing: -0.7, marginTop: 7 }, attendanceMeta: { color: palette.inverseText, fontSize: 12, lineHeight: 18, marginTop: 7, maxWidth: 250, opacity: 0.7 }, attendanceArrow: { color: palette.accent, fontSize: 28, marginTop: "auto" }, shortcutGrid: { flexDirection: "row", flexWrap: "wrap", paddingHorizontal: 22, paddingTop: 22 }, shortcut: { borderBottomColor: palette.border, borderRightColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, borderRightWidth: StyleSheet.hairlineWidth, minHeight: 105, padding: 13, width: "50%" }, shortcutLabel: { color: palette.foreground, fontSize: 11, fontWeight: "900", letterSpacing: 0.8 }, shortcutSub: { color: palette.muted, fontSize: 12, marginTop: 7 }, shortcutArrow: { color: palette.accent, fontSize: 17, marginTop: 9 }, sectionHeader: { alignItems: "center", borderBottomColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", marginTop: 24, paddingHorizontal: 22, paddingVertical: 16 }, sectionTitle: { color: palette.foreground, fontSize: 12, fontWeight: "900", letterSpacing: 0.8 }, viewAll: { color: palette.accent, fontSize: 10, fontWeight: "900", letterSpacing: 0.5 }, taskRow: { alignItems: "center", borderBottomColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 11, minHeight: 57, paddingHorizontal: 22 }, taskDot: { borderRadius: 4, height: 8, width: 8 }, taskTitle: { color: palette.foreground, flex: 1, fontSize: 15, fontWeight: "700" }, pressed: { opacity: 0.77, transform: [{ scale: 0.986 }] } });
