import { useEssGate } from "@/components/ess-gate";
import { useMemo } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import Animated, { FadeInDown } from "react-native-reanimated";
import { ScreenContainer } from "@/components/screen-container";
import { useEss } from "@/lib/ess-workspace";
import { useLumen } from "@/lib/lumen-workspace";

export default function ProjectsScreen() {
  const router = useRouter(); const { projects } = useEss(); const gate = useEssGate({ requireOnboarded: false }); const { palette } = useLumen(); const styles = useMemo(() => makeStyles(palette), [palette]);
  if (gate) return gate;
  return <ScreenContainer containerClassName={styles.container} edges={["top", "left", "right"]}><FlatList data={projects} contentContainerStyle={styles.content} keyExtractor={(project) => project.id} ListHeaderComponent={<View style={styles.hero}><Text style={styles.kicker}>ASSIGNED WORK</Text><Text style={styles.title}>PROJECTS</Text><Text style={styles.subtitle}>Track what you own, stage by stage.</Text></View>} renderItem={({ item, index }) => { const tasks = item.phases.flatMap((phase) => phase.tasks); const done = tasks.filter((task) => task.status === "done").length; const progress = Math.round(done / tasks.length * 100); return <Animated.View entering={FadeInDown.delay(index * 55).duration(240)}><Pressable accessibilityRole="button" onPress={() => router.push(`/work-project/${item.id}`)} style={({ pressed }) => [styles.project, pressed && styles.pressed]}><View style={[styles.colorBar, { backgroundColor: item.color }]} /><View style={styles.copy}><View style={styles.headline}><Text style={styles.name}>{item.name}</Text><Text style={styles.percent}>{progress}%</Text></View><Text style={styles.meta}>{item.code} · {item.client}</Text><View style={styles.track}><View style={[styles.fill, { backgroundColor: item.color, width: `${progress}%` }]} /></View><Text style={styles.status}>{item.status.toUpperCase()} · {done}/{tasks.length} COMPLETE</Text></View><Text style={styles.arrow}>→</Text></Pressable></Animated.View>; }} /></ScreenContainer>;
}
const makeStyles = (palette: ReturnType<typeof useLumen>["palette"]) => StyleSheet.create({ container: { backgroundColor: palette.background }, content: { paddingBottom: 25 }, hero: { paddingHorizontal: 22, paddingBottom: 28, paddingTop: 18 }, kicker: { color: palette.accentText, fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginBottom: 10 }, title: { color: palette.foreground, fontSize: 45, fontWeight: "900", letterSpacing: -2, lineHeight: 50 }, subtitle: { color: palette.muted, fontSize: 15, lineHeight: 21, marginTop: 8 }, project: { borderBottomColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 13, minHeight: 136, paddingHorizontal: 22, paddingVertical: 19 }, colorBar: { borderRadius: 4, height: 45, width: 7 }, copy: { flex: 1 }, headline: { alignItems: "baseline", flexDirection: "row", justifyContent: "space-between" }, name: { color: palette.foreground, flex: 1, fontSize: 21, fontWeight: "900", letterSpacing: -0.65 }, percent: { color: palette.muted, fontSize: 11, fontWeight: "900" }, meta: { color: palette.muted, fontSize: 11, fontWeight: "800", letterSpacing: 0.4, marginTop: 6 }, track: { backgroundColor: palette.surfaceStrong, borderRadius: 2, height: 5, marginTop: 16, overflow: "hidden" }, fill: { borderRadius: 2, height: 5 }, status: { color: palette.muted, fontSize: 9, fontWeight: "900", letterSpacing: 0.7, marginTop: 9 }, arrow: { color: palette.foreground, fontSize: 19 }, pressed: { opacity: 0.71 } });
