import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import Animated, { FadeInDown } from "react-native-reanimated";
import { EmptyState } from "@/components/lumen/empty-state";
import { NewItemSheet } from "@/components/lumen/new-item-sheet";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useLumen } from "@/lib/lumen-workspace";
import { projectProgress } from "@/lib/lumen-utils";
import { useMotionPreference } from "@/hooks/use-motion-preference";
export default function ProjectsScreen() { const router = useRouter(); const {palette,projects,tasks}=useLumen(); const styles=useMemo(()=>makeStyles(palette),[palette]); const reduceMotion=useMotionPreference(); const [composerOpen,setComposerOpen]=useState(false); const activeProjects=projects.filter((project)=>project.status!=="complete"); return <ScreenContainer containerClassName={styles.container} edges={["top","left","right"]}><FlatList contentContainerStyle={styles.content} data={activeProjects} keyExtractor={(project)=>project.id} ListHeaderComponent={<View style={styles.hero}><Text style={styles.kicker}>THE BIG PICTURE</Text><Text style={styles.title}>PROJECTS</Text><Text style={styles.subtitle}>Move work forward without making it louder.</Text></View>} ListEmptyComponent={<EmptyState body="Create a project to give the next step a home." kicker="READY WHEN YOU ARE" title="Start with one clear project."/>} renderItem={({item,index})=>{const progress=projectProgress(item.id,tasks);const openTasks=tasks.filter((task)=>task.projectId===item.id&&!task.completed).length;return <Animated.View entering={reduceMotion?undefined:FadeInDown.delay(index*55).duration(260)}><Pressable accessibilityLabel={`Open ${item.name} project`} accessibilityRole="button" onPress={()=>router.push(`/project/${item.id}`)} style={({pressed})=>[styles.projectRow,pressed&&styles.pressed]}><View style={[styles.projectColor,{backgroundColor:item.color}]}/><View style={styles.projectCopy}><View style={styles.projectHeading}><Text style={styles.projectName}>{item.name}</Text><Text style={styles.progressValue}>{progress}%</Text></View><Text numberOfLines={1} style={styles.description}>{item.description}</Text><View style={styles.progressTrack}><View style={[styles.progressFill,{backgroundColor:item.color,width:`${progress}%`}]}/></View><Text style={styles.taskCount}>{openTasks===0?"ALL CLEAR":`${openTasks} OPEN ${openTasks===1?"TASK":"TASKS"}`}</Text></View><Text style={styles.arrow}>→</Text></Pressable></Animated.View>}} showsVerticalScrollIndicator={false}/><Pressable accessibilityLabel="Create a project" accessibilityRole="button" onPress={()=>{haptic.light();setComposerOpen(true);}} style={({pressed})=>[styles.createButton,pressed&&styles.createPressed]}><Text style={styles.createButtonText}>NEW PROJECT</Text><Text style={styles.createButtonPlus}>+</Text></Pressable><NewItemSheet mode="project" onClose={()=>setComposerOpen(false)} visible={composerOpen}/></ScreenContainer>; }
const makeStyles=(palette:ReturnType<typeof useLumen>["palette"])=>StyleSheet.create({container:{backgroundColor:palette.background},content:{paddingBottom:102},hero:{paddingHorizontal:22,paddingBottom:28,paddingTop:18},kicker:{color:palette.accent,fontSize:10,fontWeight:"900",letterSpacing:1.2,marginBottom:10},title:{color:palette.foreground,fontSize:47,fontWeight:"900",letterSpacing:-2.2,lineHeight:53},subtitle:{color:palette.muted,fontSize:15,lineHeight:21,marginTop:8,maxWidth:280},projectRow:{borderBottomColor:palette.border,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:"row",gap:14,minHeight:148,paddingHorizontal:22,paddingVertical:20},projectColor:{borderRadius:5,height:43,marginTop:1,width:8},projectCopy:{flex:1},projectHeading:{alignItems:"baseline",flexDirection:"row",gap:8,justifyContent:"space-between"},projectName:{color:palette.foreground,flex:1,fontSize:22,fontWeight:"900",letterSpacing:-0.7},progressValue:{color:palette.muted,fontSize:12,fontWeight:"900"},description:{color:palette.muted,fontSize:13,lineHeight:19,marginTop:5},progressTrack:{backgroundColor:palette.surfaceStrong,borderRadius:2,height:5,marginTop:16,overflow:"hidden",width:"100%"},progressFill:{borderRadius:2,height:5},taskCount:{color:palette.muted,fontSize:10,fontWeight:"900",letterSpacing:0.8,marginTop:10},arrow:{color:palette.foreground,fontSize:20,fontWeight:"600",marginTop:4},createButton:{alignItems:"center",backgroundColor:palette.inverse,bottom:16,borderRadius:18,flexDirection:"row",height:55,justifyContent:"center",left:22,position:"absolute",right:22},createButtonText:{color:palette.inverseText,fontSize:11,fontWeight:"900",letterSpacing:1},createButtonPlus:{color:palette.accent,fontSize:22,fontWeight:"300",marginLeft:8},createPressed:{opacity:0.88,transform:[{scale:0.98}]},pressed:{opacity:0.72}});
