import { useMemo } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { Redirect, useRouter } from "expo-router";
import { TaskFilterBar } from "@/components/lumen/task-filter-bar";
import { TaskRow } from "@/components/lumen/task-row";
import { ScreenContainer } from "@/components/screen-container";
import { useEss } from "@/lib/ess-workspace";
import { useLumen } from "@/lib/lumen-workspace";
import { formatDate, matchesTaskFilters } from "@/lib/lumen-utils";

export default function WorkScreen() { const router = useRouter(); const { isAuthenticated } = useEss(); const { activeDate, activePriority = "all", activeTag, palette, projects, tasksForDate, toggleTask } = useLumen(); const styles = useMemo(() => makeStyles(palette), [palette]); if (!isAuthenticated) return <Redirect href="/ess/login" />; const raw = tasksForDate(activeDate); const tasks = raw.filter((task) => matchesTaskFilters(task, activePriority, activeTag)); return <ScreenContainer containerClassName={styles.container} edges={["top", "left", "right"]}><FlatList data={tasks} contentContainerStyle={styles.content} keyExtractor={(task) => task.id} ListHeaderComponent={<><View style={styles.hero}><Text style={styles.kicker}>YOUR EVERYDAY WORK</Text><Text style={styles.title}>TASKS</Text><Text style={styles.date}>{formatDate(activeDate)}</Text></View><View style={styles.jumpRow}><Pressable onPress={() => router.push("/(tabs)/calendar")} style={styles.jump}><Text style={styles.jumpLabel}>MONTH VIEW</Text><Text style={styles.jumpArrow}>→</Text></Pressable><Pressable onPress={() => router.push("/(tabs)/focus")} style={styles.jump}><Text style={styles.jumpLabel}>FOCUS MODE</Text><Text style={styles.jumpArrow}>→</Text></Pressable></View><TaskFilterBar /><View style={styles.section}><Text style={styles.sectionTitle}>TASK LIST</Text><Text style={styles.sectionMeta}>{tasks.length} ITEMS</Text></View></>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyKicker}>{raw.length ? "NO MATCHES" : "THE DAY IS CLEAR"}</Text><Text style={styles.emptyTitle}>{raw.length ? "Try another filter." : "There is room for your best work."}</Text></View>} renderItem={({ item }) => { const project = projects.find((candidate) => candidate.id === item.projectId); return <TaskRow task={item} projectName={project?.name} projectColor={project?.color} onToggle={() => toggleTask(item.id)} />; }} /></ScreenContainer>; }
const makeStyles = (palette: ReturnType<typeof useLumen>["palette"]) => StyleSheet.create({ container:{backgroundColor:palette.background},content:{paddingBottom:24},hero:{paddingHorizontal:22,paddingBottom:22,paddingTop:18},kicker:{color:palette.accent,fontSize:10,fontWeight:"900",letterSpacing:1.1,marginBottom:10},title:{color:palette.foreground,fontSize:45,fontWeight:"900",letterSpacing:-2,lineHeight:50},date:{color:palette.muted,fontSize:13,fontWeight:"700",marginTop:7},jumpRow:{borderBottomColor:palette.border,borderTopColor:palette.border,borderBottomWidth:StyleSheet.hairlineWidth,borderTopWidth:StyleSheet.hairlineWidth,flexDirection:"row"},jump:{alignItems:"center",borderRightColor:palette.border,borderRightWidth:StyleSheet.hairlineWidth,flex:1,flexDirection:"row",justifyContent:"space-between",minHeight:54,paddingHorizontal:17},jumpLabel:{color:palette.foreground,fontSize:10,fontWeight:"900",letterSpacing:0.55},jumpArrow:{color:palette.accent,fontSize:18},section:{alignItems:"center",borderBottomColor:palette.border,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:"row",justifyContent:"space-between",paddingHorizontal:22,paddingVertical:16},sectionTitle:{color:palette.foreground,fontSize:12,fontWeight:"900",letterSpacing:0.8},sectionMeta:{color:palette.muted,fontSize:10,fontWeight:"900"},empty:{gap:7,paddingHorizontal:22,paddingVertical:28},emptyKicker:{color:palette.accent,fontSize:10,fontWeight:"900",letterSpacing:0.9},emptyTitle:{color:palette.foreground,fontSize:21,fontWeight:"900",letterSpacing:-0.5}});
