import { BackButton } from "@/components/pmec";
import { performSafeBack } from "@/lib/pmec-navigation";
import { useMemo } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useEss } from "@/lib/ess-workspace";
import type { ProjectTaskStatus } from "@/lib/ess-types";
import { useLumen } from "@/lib/lumen-workspace";

const nextStatus: Record<ProjectTaskStatus, ProjectTaskStatus> = { todo: "in_progress", in_progress: "done", done: "todo" };
export default function WorkProjectDetail() { const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { projects, updateProjectTask } = useEss(); const { palette } = useLumen(); const styles = useMemo(() => makeStyles(palette), [palette]); const project = projects.find((item) => item.id === id); if (!project) return <ScreenContainer containerClassName={styles.container} edges={["top", "bottom", "left", "right"]}><View style={styles.missing}><Text style={styles.name}>PROJECT NOT FOUND</Text><Pressable accessibilityRole="button" accessibilityLabel="Back to Projects" onPress={() => performSafeBack(router, "/projects")}><Text style={styles.returnText}>RETURN</Text></Pressable></View></ScreenContainer>; const tasks = project.phases.flatMap((phase) => phase.tasks.map((task) => ({ ...task, phase }))); const done = tasks.filter((task) => task.status === "done").length; const progress = Math.round(done / tasks.length * 100); return <ScreenContainer containerClassName={styles.container} edges={["top", "left", "right"]}><FlatList data={tasks} keyExtractor={(task) => task.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.top}><BackButton fallback="/projects" label="Back to Projects" /><Text style={styles.topLabel}>PROJECT WORK</Text></View><View style={styles.hero}><View style={[styles.mark, { backgroundColor: project.color }]} /><Text style={styles.name}>{project.name.toUpperCase()}</Text><Text style={styles.meta}>{project.code} · {project.client}</Text><View style={styles.progressTrack}><View style={[styles.progress, { backgroundColor: project.color, width: `${progress}%` }]} /></View><Text style={styles.progressText}>{progress}% COMPLETE · {done}/{tasks.length} TASKS</Text></View><Text style={styles.listTitle}>WORK ITEMS</Text></>} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => { haptic.selection(); updateProjectTask(project.id, item.phase.id, item.id, nextStatus[item.status]); }} style={({ pressed }) => [styles.task, pressed && styles.pressed]}><View style={[styles.statusDot, { backgroundColor: item.status === "done" ? palette.success : item.status === "in_progress" ? palette.accent : palette.border }]} /><View style={styles.taskCopy}><Text style={styles.taskTitle}>{item.title}</Text><Text style={styles.taskMeta}>{item.phase.name.toUpperCase()} · {item.status.replace("_", " ").toUpperCase()}</Text></View><Text style={styles.cycle}>↻</Text></Pressable>} /></ScreenContainer>; }
const makeStyles = (palette: ReturnType<typeof useLumen>["palette"]) => StyleSheet.create({ container: { backgroundColor: palette.background }, content: { paddingBottom: 24 }, top: { alignItems: "center", flexDirection: "row", gap: 12, paddingHorizontal: 18, paddingTop: 10 }, back: { alignItems: "center", borderColor: palette.border, borderRadius: 16, borderWidth: 1, height: 34, justifyContent: "center", width: 34 }, backText: { color: palette.foreground, fontSize: 20 }, topLabel: { color: palette.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, hero: { padding: 22 }, mark: { borderRadius: 3, height: 5, marginBottom: 18, width: 52 }, name: { color: palette.foreground, fontSize: 34, fontWeight: "900", letterSpacing: -1.4, lineHeight: 39 }, meta: { color: palette.muted, fontSize: 11, fontWeight: "800", letterSpacing: 0.6, marginTop: 8 }, progressTrack: { backgroundColor: palette.surfaceStrong, borderRadius: 3, height: 6, marginTop: 24, overflow: "hidden" }, progress: { borderRadius: 3, height: 6 }, progressText: { color: palette.muted, fontSize: 10, fontWeight: "900", letterSpacing: 0.7, marginTop: 10 }, listTitle: { borderBottomColor: palette.border, borderTopColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, borderTopWidth: StyleSheet.hairlineWidth, color: palette.foreground, fontSize: 12, fontWeight: "900", letterSpacing: 0.8, paddingHorizontal: 22, paddingVertical: 16 }, task: { alignItems: "center", borderBottomColor: palette.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 13, minHeight: 69, paddingHorizontal: 22 }, statusDot: { borderRadius: 6, height: 12, width: 12 }, taskCopy: { flex: 1 }, taskTitle: { color: palette.foreground, fontSize: 15, fontWeight: "800" }, taskMeta: { color: palette.muted, fontSize: 9, fontWeight: "900", letterSpacing: 0.5, marginTop: 5 }, cycle: { color: palette.muted, fontSize: 18 }, missing: { alignItems: "center", flex: 1, justifyContent: "center" }, returnText: { color: palette.accentText, fontSize: 11, fontWeight: "900", letterSpacing: 1, marginTop: 16 }, pressed: { opacity: 0.7 } });
